// Code generated by am-gen; DO NOT EDIT.
//go:build tinygo

package machine

// ArgsToArgs copies identical fields from [ATRpc] to [AT].
func ArgsToArgs(argsRpc *ATRpc) AT {
	return AT{
		CalledStates: argsRpc.CalledStates,
		Err:          argsRpc.Err,
		ErrTrace:     argsRpc.ErrTrace,
		Event:        argsRpc.Event,
		Panic:        argsRpc.Panic,
		TargetStates: argsRpc.TargetStates,
		TimeAfter:    argsRpc.TimeAfter,
		TimeBefore:   argsRpc.TimeBefore,
	}
}
