// Code generated by am-gen; DO NOT EDIT.
//go:build tinygo

package states

import am "github.com/pancsta/asyncmachine-go/pkg/machine"

// S is a type alias for a list of state names.
type S = am.S

// ///// ///// /////

// ///// SHARED

// ///// ///// /////

// SharedStatesDef contains states for Shared.
type SharedStatesDef struct {
	*am.StatesBase
	ErrNetworkTimeout string
	ErrRpc            string
	ErrDelivery       string
	HandshakeDone     string
	Handshaking       string
	ErrNetwork        string
	ErrHandlerTimeout string
	Start             string
	Ready             string
	Healthcheck       string
	Heartbeat         string
	ErrOnClient       string
	ErrProviding      string
	ErrSendPayload    string
	SendPayload       string
}

// SharedGroupsDef contains all the state groups of the Shared state schema.
type SharedGroupsDef struct {
	Handshake S
}

// SharedSchema represents all relations and properties of SharedStates.
var SharedSchema = am.Schema{
	ssS.ErrDelivery: {Require: S{ssS.Exception}},
	ssS.ErrHandlerTimeout: {
		Add:     S{ssS.Exception},
		Multi:   true,
		Require: S{ssS.Exception},
	},
	ssS.ErrNetwork:        {Require: S{ssS.Exception}},
	ssS.ErrNetworkTimeout: {Require: S{ssS.Exception}},
	ssS.ErrOnClient:       {Require: S{ssS.Exception}},
	ssS.ErrProviding:      {Require: S{ssS.Exception}},
	ssS.ErrRpc:            {Require: S{ssS.Exception}},
	ssS.ErrSendPayload:    {Require: S{ssS.Exception}},
	ssS.Exception:         {Multi: true},
	ssS.HandshakeDone: {
		Remove:  S{ssS.Handshaking, ssS.HandshakeDone},
		Require: S{ssS.Start},
	},
	ssS.Handshaking: {
		Remove:  S{ssS.Handshaking, ssS.HandshakeDone},
		Require: S{ssS.Start},
	},
	ssS.Healthcheck: {Multi: true},
	ssS.Heartbeat:   {},
	ssS.Ready:       {Require: S{ssS.Start}},
	ssS.SendPayload: {Multi: true},
	ssS.Start:       {},
}

// EXPORTS AND GROUPS
var (
	ssS = SharedStatesDef{
		ErrDelivery:       "ErrDelivery",
		ErrHandlerTimeout: "ErrHandlerTimeout",
		ErrNetwork:        "ErrNetwork",
		ErrNetworkTimeout: "ErrNetworkTimeout",
		ErrOnClient:       "ErrOnClient",
		ErrProviding:      "ErrProviding",
		ErrRpc:            "ErrRpc",
		ErrSendPayload:    "ErrSendPayload",
		HandshakeDone:     "HandshakeDone",
		Handshaking:       "Handshaking",
		Healthcheck:       "Healthcheck",
		Heartbeat:         "Heartbeat",
		Ready:             "Ready",
		SendPayload:       "SendPayload",
		Start:             "Start",
		StatesBase:        &am.StatesBase{Exception: "Exception"},
	}
	sgS = SharedGroupsDef{Handshake: S{ssS.Handshaking, ssS.HandshakeDone}}

	// SharedStates contains all the states for the Shared state schema.
	SharedStates = ssS

	// SharedGroups contains all the state groups for the Shared state schema.
	SharedGroups = sgS
)

func init() {
	ssS.SetNames(S{"Exception", "ErrNetworkTimeout", "ErrRpc", "ErrDelivery", "HandshakeDone", "Handshaking", "ErrNetwork", "ErrHandlerTimeout", "Start", "Ready", "Healthcheck", "Heartbeat", "ErrOnClient", "ErrProviding", "ErrSendPayload", "SendPayload"})
	groups := map[string][]int{"Handshake": {5, 4}}
	ssS.SetStateGroups(groups, []string{"Handshake"})
}

// ///// ///// /////

// ///// STATE SOURCE

// ///// ///// /////

// StateSourceStatesDef contains states for StateSource.
type StateSourceStatesDef struct {
	*am.StatesBase
	ErrOnClient    string
	ErrProviding   string
	ErrSendPayload string
	SendPayload    string
}

// StateSourceGroupsDef contains all the state groups of the StateSource state schema.
type StateSourceGroupsDef struct{}

// StateSourceSchema represents all relations and properties of StateSourceStates.
var StateSourceSchema = am.Schema{
	ssSS.ErrOnClient:    {Require: S{ssSS.Exception}},
	ssSS.ErrProviding:   {Require: S{ssSS.Exception}},
	ssSS.ErrSendPayload: {Require: S{ssSS.Exception}},
	ssSS.Exception:      {},
	ssSS.SendPayload:    {Multi: true},
}

// EXPORTS AND GROUPS
var (
	ssSS = StateSourceStatesDef{
		ErrOnClient:    "ErrOnClient",
		ErrProviding:   "ErrProviding",
		ErrSendPayload: "ErrSendPayload",
		SendPayload:    "SendPayload",
		StatesBase:     &am.StatesBase{Exception: "Exception"},
	}
	sgSS = StateSourceGroupsDef{}

	// StateSourceStates contains all the states for the StateSource state schema.
	StateSourceStates = ssSS

	// StateSourceGroups contains all the state groups for the StateSource state schema.
	StateSourceGroups = sgSS
)

func init() {
	ssSS.SetNames(S{"Exception", "ErrOnClient", "ErrProviding", "ErrSendPayload", "SendPayload"})
	groups := map[string][]int{}
	ssSS.SetStateGroups(groups, []string{})
}

// ///// ///// /////

// ///// SERVER

// ///// ///// /////

// ServerStatesDef contains states for Server.
type ServerStatesDef struct {
	*am.StatesBase
	Ready             string
	RpcStarting       string
	RpcAccepting      string
	RpcReady          string
	ClientConnected   string
	HandshakeDone     string
	MetricSync        string
	WebSocketTunnel   string
	ErrNetworkTimeout string
	ErrRpc            string
	ErrDelivery       string
	Handshaking       string
	ErrNetwork        string
	ErrHandlerTimeout string
	Start             string
	Healthcheck       string
	Heartbeat         string
	ErrOnClient       string
	ErrProviding      string
	ErrSendPayload    string
	SendPayload       string
}

// ServerGroupsDef contains all the state groups of the Server state schema.
type ServerGroupsDef struct {
	Handshake S
	Rpc       S
}

// ServerSchema represents all relations and properties of ServerStates.
var ServerSchema = am.Schema{
	ssS2.ClientConnected: {Require: S{ssS2.RpcReady}},
	ssS2.ErrDelivery:     {Require: S{ssS2.Exception}},
	ssS2.ErrHandlerTimeout: {
		Add:     S{ssS2.Exception},
		Multi:   true,
		Require: S{ssS2.Exception},
	},
	ssS2.ErrNetwork: {
		Remove:  S{ssS2.ClientConnected},
		Require: S{ssS2.Exception},
	},
	ssS2.ErrNetworkTimeout: {Require: S{ssS2.Exception}},
	ssS2.ErrOnClient:       {Require: S{ssS2.Exception}},
	ssS2.ErrProviding:      {Require: S{ssS2.Exception}},
	ssS2.ErrRpc:            {Require: S{ssS2.Exception}},
	ssS2.ErrSendPayload:    {Require: S{ssS2.Exception}},
	ssS2.Exception:         {Multi: true},
	ssS2.HandshakeDone: {
		Remove:  S{ssS2.Handshaking, ssS2.HandshakeDone, ssS2.Exception},
		Require: S{ssS2.Start, ssS2.ClientConnected},
	},
	ssS2.Handshaking: {
		Remove:  S{ssS2.Handshaking, ssS2.HandshakeDone},
		Require: S{ssS2.Start},
	},
	ssS2.Healthcheck: {Multi: true},
	ssS2.Heartbeat:   {},
	ssS2.MetricSync:  {Multi: true},
	ssS2.Ready: {
		Auto:    true,
		Require: S{ssS2.HandshakeDone, ssS2.RpcReady},
	},
	ssS2.RpcAccepting: {
		Remove:  S{ssS2.RpcStarting, ssS2.RpcAccepting, ssS2.RpcReady},
		Require: S{ssS2.Start},
	},
	ssS2.RpcReady: {
		Remove:  S{ssS2.RpcStarting, ssS2.RpcAccepting, ssS2.RpcReady},
		Require: S{ssS2.Start},
	},
	ssS2.RpcStarting: {
		Remove:  S{ssS2.RpcStarting, ssS2.RpcAccepting, ssS2.RpcReady},
		Require: S{ssS2.Start},
	},
	ssS2.SendPayload:     {Multi: true},
	ssS2.Start:           {Add: S{ssS2.RpcStarting}},
	ssS2.WebSocketTunnel: {},
}

// EXPORTS AND GROUPS
var (
	ssS2 = ServerStatesDef{
		ClientConnected:   "ClientConnected",
		ErrDelivery:       "ErrDelivery",
		ErrHandlerTimeout: "ErrHandlerTimeout",
		ErrNetwork:        "ErrNetwork",
		ErrNetworkTimeout: "ErrNetworkTimeout",
		ErrOnClient:       "ErrOnClient",
		ErrProviding:      "ErrProviding",
		ErrRpc:            "ErrRpc",
		ErrSendPayload:    "ErrSendPayload",
		HandshakeDone:     "HandshakeDone",
		Handshaking:       "Handshaking",
		Healthcheck:       "Healthcheck",
		Heartbeat:         "Heartbeat",
		MetricSync:        "MetricSync",
		Ready:             "Ready",
		RpcAccepting:      "RpcAccepting",
		RpcReady:          "RpcReady",
		RpcStarting:       "RpcStarting",
		SendPayload:       "SendPayload",
		Start:             "Start",
		StatesBase:        &am.StatesBase{Exception: "Exception"},
		WebSocketTunnel:   "WebSocketTunnel",
	}
	sgS2 = ServerGroupsDef{
		Handshake: S{ssS2.Handshaking, ssS2.HandshakeDone},
		Rpc:       S{ssS2.RpcStarting, ssS2.RpcAccepting, ssS2.RpcReady},
	}

	// ServerStates contains all the states for the Server state schema.
	ServerStates = ssS2

	// ServerGroups contains all the state groups for the Server state schema.
	ServerGroups = sgS2
)

func init() {
	ssS2.SetNames(S{"Exception", "Ready", "RpcStarting", "RpcAccepting", "RpcReady", "ClientConnected", "HandshakeDone", "MetricSync", "WebSocketTunnel", "ErrNetworkTimeout", "ErrRpc", "ErrDelivery", "Handshaking", "ErrNetwork", "ErrHandlerTimeout", "Start", "Healthcheck", "Heartbeat", "ErrOnClient", "ErrProviding", "ErrSendPayload", "SendPayload"})
	groups := map[string][]int{
		"Handshake": {12, 6},
		"Rpc":       {2, 3, 4},
	}
	ssS2.SetStateGroups(groups, []string{"Handshake", "Rpc"})
}

// ///// ///// /////

// ///// CLIENT

// ///// ///// /////

// ClientStatesDef contains states for Client.
type ClientStatesDef struct {
	*am.StatesBase
	RetryingCall      string
	CallRetryFailed   string
	RetryingConn      string
	ConnRetryFailed   string
	Ready             string
	HandshakeDone     string
	ServerDelivering  string
	ServerPayload     string
	MetricSync        string
	ErrNetworkTimeout string
	ErrRpc            string
	ErrDelivery       string
	Handshaking       string
	ErrNetwork        string
	ErrHandlerTimeout string
	Start             string
	Healthcheck       string
	Heartbeat         string
	ErrOnClient       string
	ErrProviding      string
	ErrSendPayload    string
	SendPayload       string
	ErrConnecting     string
	Connecting        string
	Connected         string
	Disconnecting     string
	Disconnected      string
}

// ClientGroupsDef contains all the state groups of the Client state schema.
type ClientGroupsDef struct {
	Handshake S
	Connected S
}

// ClientSchema represents all relations and properties of ClientStates.
var ClientSchema = am.Schema{
	ssC.CallRetryFailed: {
		Add:    S{ssC.ErrNetwork, ssC.Exception},
		Remove: S{ssC.RetryingCall},
	},
	ssC.ConnRetryFailed: {Remove: S{ssC.Start}},
	ssC.Connected: {
		Add:     S{ssC.Handshaking},
		Remove:  S{ssC.Connecting, ssC.Connected, ssC.Disconnecting, ssC.Disconnected, ssC.RetryingConn},
		Require: S{ssC.Start},
	},
	ssC.Connecting: {
		Remove:  S{ssC.Connecting, ssC.Connected, ssC.Disconnecting, ssC.Disconnected},
		Require: S{ssC.Start},
	},
	ssC.Disconnected: {
		Auto:   true,
		Remove: S{ssC.Connecting, ssC.Connected, ssC.Disconnecting, ssC.Disconnected},
	},
	ssC.Disconnecting: {Remove: S{ssC.Connecting, ssC.Connected, ssC.Disconnecting, ssC.Disconnected}},
	ssC.ErrConnecting: {Require: S{ssC.Exception}},
	ssC.ErrDelivery:   {Require: S{ssC.Exception}},
	ssC.ErrHandlerTimeout: {
		Add:     S{ssC.Exception},
		Multi:   true,
		Require: S{ssC.Exception},
	},
	ssC.ErrNetwork: {
		Remove:  S{ssC.Connecting},
		Require: S{ssC.Exception},
	},
	ssC.ErrNetworkTimeout: {Require: S{ssC.Exception}},
	ssC.ErrOnClient:       {Require: S{ssC.Exception}},
	ssC.ErrProviding:      {Require: S{ssC.Exception}},
	ssC.ErrRpc:            {Require: S{ssC.Exception}},
	ssC.ErrSendPayload:    {Require: S{ssC.Exception}},
	ssC.Exception:         {Multi: true},
	ssC.HandshakeDone: {
		Remove:  S{ssC.Handshaking, ssC.HandshakeDone},
		Require: S{ssC.Start, ssC.Connected},
	},
	ssC.Handshaking: {
		Remove:  S{ssC.Handshaking, ssC.HandshakeDone},
		Require: S{ssC.Start, ssC.Connected},
	},
	ssC.Healthcheck: {Multi: true},
	ssC.Heartbeat:   {},
	ssC.MetricSync:  {Multi: true},
	ssC.Ready: {
		Auto:    true,
		Require: S{ssC.HandshakeDone},
	},
	ssC.RetryingCall: {Require: S{ssC.Start}},
	ssC.RetryingConn: {Require: S{ssC.Start}},
	ssC.SendPayload:  {Multi: true},
	ssC.ServerDelivering: {
		Multi:   true,
		Require: S{ssC.Connected},
	},
	ssC.ServerPayload: {
		Multi:   true,
		Require: S{ssC.Connected},
	},
	ssC.Start: {
		Add:    S{ssC.Connecting},
		Remove: S{ssC.ConnRetryFailed},
	},
}

// EXPORTS AND GROUPS
var (
	ssC = ClientStatesDef{
		CallRetryFailed:   "CallRetryFailed",
		ConnRetryFailed:   "ConnRetryFailed",
		Connected:         "Connected",
		Connecting:        "Connecting",
		Disconnected:      "Disconnected",
		Disconnecting:     "Disconnecting",
		ErrConnecting:     "ErrConnecting",
		ErrDelivery:       "ErrDelivery",
		ErrHandlerTimeout: "ErrHandlerTimeout",
		ErrNetwork:        "ErrNetwork",
		ErrNetworkTimeout: "ErrNetworkTimeout",
		ErrOnClient:       "ErrOnClient",
		ErrProviding:      "ErrProviding",
		ErrRpc:            "ErrRpc",
		ErrSendPayload:    "ErrSendPayload",
		HandshakeDone:     "HandshakeDone",
		Handshaking:       "Handshaking",
		Healthcheck:       "Healthcheck",
		Heartbeat:         "Heartbeat",
		MetricSync:        "MetricSync",
		Ready:             "Ready",
		RetryingCall:      "RetryingCall",
		RetryingConn:      "RetryingConn",
		SendPayload:       "SendPayload",
		ServerDelivering:  "ServerDelivering",
		ServerPayload:     "ServerPayload",
		Start:             "Start",
		StatesBase:        &am.StatesBase{Exception: "Exception"},
	}
	sgC = ClientGroupsDef{
		Connected: S{ssC.Connecting, ssC.Connected, ssC.Disconnecting, ssC.Disconnected},
		Handshake: S{ssC.Handshaking, ssC.HandshakeDone},
	}

	// ClientStates contains all the states for the Client state schema.
	ClientStates = ssC

	// ClientGroups contains all the state groups for the Client state schema.
	ClientGroups = sgC
)

func init() {
	ssC.SetNames(S{"Exception", "RetryingCall", "CallRetryFailed", "RetryingConn", "ConnRetryFailed", "Ready", "HandshakeDone", "ServerDelivering", "ServerPayload", "MetricSync", "ErrNetworkTimeout", "ErrRpc", "ErrDelivery", "Handshaking", "ErrNetwork", "ErrHandlerTimeout", "Start", "Healthcheck", "Heartbeat", "ErrOnClient", "ErrProviding", "ErrSendPayload", "SendPayload", "ErrConnecting", "Connecting", "Connected", "Disconnecting", "Disconnected"})
	groups := map[string][]int{
		"Connected": {24, 25, 26, 27},
		"Handshake": {13, 6},
	}
	ssC.SetStateGroups(groups, []string{"Handshake", "Connected"})
}

// ///// ///// /////

// ///// MUX

// ///// ///// /////

// MuxStatesDef contains states for Mux.
type MuxStatesDef struct {
	*am.StatesBase
	Ready             string
	ClientConnected   string
	HasClients        string
	NewServerErr      string
	ErrNetwork        string
	ErrHandlerTimeout string
	Start             string
	Healthcheck       string
	Heartbeat         string
}

// MuxGroupsDef contains all the state groups of the Mux state schema.
type MuxGroupsDef struct{}

// MuxSchema represents all relations and properties of MuxStates.
var MuxSchema = am.Schema{
	ssM.ClientConnected: {
		Multi:   true,
		Require: S{ssM.Start},
	},
	ssM.ErrHandlerTimeout: {
		Add:     S{ssM.Exception},
		Multi:   true,
		Require: S{ssM.Exception},
	},
	ssM.ErrNetwork: {
		Add:     S{ssM.Exception},
		Multi:   true,
		Require: S{ssM.Exception},
	},
	ssM.Exception: {
		Multi:  true,
		Remove: S{ssM.Ready},
	},
	ssM.HasClients:   {Require: S{ssM.Start}},
	ssM.Healthcheck:  {Multi: true},
	ssM.Heartbeat:    {},
	ssM.NewServerErr: {},
	ssM.Ready:        {Require: S{ssM.Start}},
	ssM.Start:        {},
}

// EXPORTS AND GROUPS
var (
	ssM = MuxStatesDef{
		ClientConnected:   "ClientConnected",
		ErrHandlerTimeout: "ErrHandlerTimeout",
		ErrNetwork:        "ErrNetwork",
		HasClients:        "HasClients",
		Healthcheck:       "Healthcheck",
		Heartbeat:         "Heartbeat",
		NewServerErr:      "NewServerErr",
		Ready:             "Ready",
		Start:             "Start",
		StatesBase:        &am.StatesBase{Exception: "Exception"},
	}
	sgM = MuxGroupsDef{}

	// MuxStates contains all the states for the Mux state schema.
	MuxStates = ssM

	// MuxGroups contains all the state groups for the Mux state schema.
	MuxGroups = sgM
)

func init() {
	ssM.SetNames(S{"Exception", "Ready", "ClientConnected", "HasClients", "NewServerErr", "ErrNetwork", "ErrHandlerTimeout", "Start", "Healthcheck", "Heartbeat"})
	groups := map[string][]int{}
	ssM.SetStateGroups(groups, []string{})
}

// ///// ///// /////

// ///// CONSUMER

// ///// ///// /////

// ConsumerStatesDef contains states for Consumer.
type ConsumerStatesDef struct {
	*am.StatesBase
	ServerPayload string
}

// ConsumerGroupsDef contains all the state groups of the Consumer state schema.
type ConsumerGroupsDef struct{}

// ConsumerSchema represents all relations and properties of ConsumerStates.
var ConsumerSchema = am.Schema{
	ssC2.Exception:     {},
	ssC2.ServerPayload: {Multi: true},
}

// EXPORTS AND GROUPS
var (
	ssC2 = ConsumerStatesDef{
		ServerPayload: "ServerPayload",
		StatesBase:    &am.StatesBase{Exception: "Exception"},
	}
	sgC2 = ConsumerGroupsDef{}

	// ConsumerStates contains all the states for the Consumer state schema.
	ConsumerStates = ssC2

	// ConsumerGroups contains all the state groups for the Consumer state schema.
	ConsumerGroups = sgC2
)

func init() {
	ssC2.SetNames(S{"Exception", "ServerPayload"})
	groups := map[string][]int{}
	ssC2.SetStateGroups(groups, []string{})
}
