// Code generated by am-gen; DO NOT EDIT.
//go:build tinygo

package states

import am "github.com/pancsta/asyncmachine-go/pkg/machine"

// S is a type alias for a list of state names.
type S = am.S

// ///// ///// /////

// ///// BASIC

// ///// ///// /////

// BasicStatesDef contains states for Basic.
type BasicStatesDef struct {
	*am.StatesBase
	ErrNetwork        string
	ErrHandlerTimeout string
	Start             string
	Ready             string
	Healthcheck       string
	Heartbeat         string
}

// BasicGroupsDef contains all the state groups of the Basic state schema.
type BasicGroupsDef struct{}

// BasicSchema represents all relations and properties of BasicStates.
var BasicSchema = am.Schema{
	ssB.ErrHandlerTimeout: {
		Add:     S{ssB.Exception},
		Multi:   true,
		Require: S{ssB.Exception},
	},
	ssB.ErrNetwork: {
		Add:     S{ssB.Exception},
		Multi:   true,
		Require: S{ssB.Exception},
	},
	ssB.Exception:   {Multi: true},
	ssB.Healthcheck: {Multi: true},
	ssB.Heartbeat:   {},
	ssB.Ready:       {Require: S{ssB.Start}},
	ssB.Start:       {},
}

// EXPORTS AND GROUPS
var (
	ssB = BasicStatesDef{
		ErrHandlerTimeout: "ErrHandlerTimeout",
		ErrNetwork:        "ErrNetwork",
		Healthcheck:       "Healthcheck",
		Heartbeat:         "Heartbeat",
		Ready:             "Ready",
		Start:             "Start",
		StatesBase:        &am.StatesBase{Exception: "Exception"},
	}
	sgB = BasicGroupsDef{}

	// BasicStates contains all the states for the Basic state schema.
	BasicStates = ssB

	// BasicGroups contains all the state groups for the Basic state schema.
	BasicGroups = sgB
)

func init() {
	ssB.SetNames(S{"Exception", "ErrNetwork", "ErrHandlerTimeout", "Start", "Ready", "Healthcheck", "Heartbeat"})
	groups := map[string][]int{}
	ssB.SetStateGroups(groups, []string{})
}

// ///// ///// /////

// ///// CONNECTED

// ///// ///// /////

// ConnectedStatesDef contains states for Connected.
type ConnectedStatesDef struct {
	*am.StatesBase
	ErrConnecting string
	Connecting    string
	Connected     string
	Disconnecting string
	Disconnected  string
}

// ConnectedGroupsDef contains all the state groups of the Connected state schema.
type ConnectedGroupsDef struct {
	Connected S
}

// ConnectedSchema represents all relations and properties of ConnectedStates.
var ConnectedSchema = am.Schema{
	ssC.Connected: {
		Remove:  S{ssC.Connecting, ssC.Connected, ssC.Disconnecting, ssC.Disconnected},
		Require: S{"Start"},
	},
	ssC.Connecting: {
		Remove:  S{ssC.Connecting, ssC.Connected, ssC.Disconnecting, ssC.Disconnected},
		Require: S{"Start"},
	},
	ssC.Disconnected: {
		Auto:   true,
		Remove: S{ssC.Connecting, ssC.Connected, ssC.Disconnecting, ssC.Disconnected},
	},
	ssC.Disconnecting: {Remove: S{ssC.Connecting, ssC.Connected, ssC.Disconnecting, ssC.Disconnected}},
	ssC.ErrConnecting: {Require: S{ssC.Exception}},
	ssC.Exception:     {},
}

// EXPORTS AND GROUPS
var (
	ssC = ConnectedStatesDef{
		Connected:     "Connected",
		Connecting:    "Connecting",
		Disconnected:  "Disconnected",
		Disconnecting: "Disconnecting",
		ErrConnecting: "ErrConnecting",
		StatesBase:    &am.StatesBase{Exception: "Exception"},
	}
	sgC = ConnectedGroupsDef{Connected: S{ssC.Connecting, ssC.Connected, ssC.Disconnecting, ssC.Disconnected}}

	// ConnectedStates contains all the states for the Connected state schema.
	ConnectedStates = ssC

	// ConnectedGroups contains all the state groups for the Connected state schema.
	ConnectedGroups = sgC
)

func init() {
	ssC.SetNames(S{"Exception", "ErrConnecting", "Connecting", "Connected", "Disconnecting", "Disconnected"})
	groups := map[string][]int{"Connected": {2, 3, 4, 5}}
	ssC.SetStateGroups(groups, []string{"Connected"})
}

// ///// ///// /////

// ///// CONN POOL

// ///// ///// /////

// ConnPoolStatesDef contains states for ConnPool.
type ConnPoolStatesDef struct {
	*am.StatesBase
	ErrConnecting  string
	Connecting     string
	Connected      string
	ConnectedFully string
	Disconnecting  string
	Disconnected   string
}

// ConnPoolGroupsDef contains all the state groups of the ConnPool state schema.
type ConnPoolGroupsDef struct {
	Connected S
}

// ConnPoolSchema represents all relations and properties of ConnPoolStates.
var ConnPoolSchema = am.Schema{
	ssCP.Connected: {
		Remove:  S{ssCP.Disconnected},
		Require: S{"Start"},
	},
	ssCP.ConnectedFully: {
		Remove:  S{ssCP.Disconnected},
		Require: S{ssCP.Connected},
	},
	ssCP.Connecting: {
		Remove:  S{ssCP.Disconnecting},
		Require: S{"Start"},
	},
	ssCP.Disconnected:  {Remove: S{ssCP.Connecting, ssCP.ConnectedFully, ssCP.Disconnecting}},
	ssCP.Disconnecting: {Remove: S{ssCP.ConnectedFully, ssCP.Connected, ssCP.Connecting}},
	ssCP.ErrConnecting: {Require: S{ssCP.Exception}},
	ssCP.Exception:     {},
}

// EXPORTS AND GROUPS
var (
	ssCP = ConnPoolStatesDef{
		Connected:      "Connected",
		ConnectedFully: "ConnectedFully",
		Connecting:     "Connecting",
		Disconnected:   "Disconnected",
		Disconnecting:  "Disconnecting",
		ErrConnecting:  "ErrConnecting",
		StatesBase:     &am.StatesBase{Exception: "Exception"},
	}
	sgCP = ConnPoolGroupsDef{Connected: S{ssCP.Connected, ssCP.Disconnected}}

	// ConnPoolStates contains all the states for the ConnPool state schema.
	ConnPoolStates = ssCP

	// ConnPoolGroups contains all the state groups for the ConnPool state schema.
	ConnPoolGroups = sgCP
)

func init() {
	ssCP.SetNames(S{"ErrConnecting", "Connecting", "Connected", "ConnectedFully", "Disconnecting", "Disconnected", "Exception"})
	groups := map[string][]int{"Connected": {2, 5}}
	ssCP.SetStateGroups(groups, []string{"Connected"})
}

// ///// ///// /////

// ///// DISPOSED

// ///// ///// /////

// DisposedStatesDef contains states for Disposed.
type DisposedStatesDef struct {
	*am.StatesBase
	RegisterDisposal string
	Disposing        string
	Disposed         string
}

// DisposedGroupsDef contains all the state groups of the Disposed state schema.
type DisposedGroupsDef struct{}

// DisposedSchema represents all relations and properties of DisposedStates.
var DisposedSchema = am.Schema{
	ssD.Disposed:         {Remove: S{ssD.Disposing, "Start"}},
	ssD.Disposing:        {Remove: S{"Start"}},
	ssD.Exception:        {},
	ssD.RegisterDisposal: {Multi: true},
}

// EXPORTS AND GROUPS
var (
	ssD = DisposedStatesDef{
		Disposed:         "Disposed",
		Disposing:        "Disposing",
		RegisterDisposal: "RegisterDisposal",
		StatesBase:       &am.StatesBase{Exception: "Exception"},
	}
	sgD = DisposedGroupsDef{}

	// DisposedStates contains all the states for the Disposed state schema.
	DisposedStates = ssD

	// DisposedGroups contains all the state groups for the Disposed state schema.
	DisposedGroups = sgD
)

func init() {
	ssD.SetNames(S{"Exception", "RegisterDisposal", "Disposing", "Disposed"})
	groups := map[string][]int{}
	ssD.SetStateGroups(groups, []string{})
}
