version: '3'

dotenv: ['.env']

env:
  GOFMT: gofumpt

tasks:

  demo:
    cmds:
      - task: install-deps
      - task: build-protobufs
      - task: test
      - task: start

  build:
    cmds:
      - go build src/machine/*
    silent: true

  test:
    cmds:
      - task: clean
      - go test ./...

  test-verbose:
    cmds:
      - go test ./... -v

  clean:
    cmds:
      - go clean -testcache

  cloc:
    cmds:
      - gocloc pkg/machine --not-match=_test\.go
      - gocloc pkg/machine/*_test.go
      - gocloc examples
      - gocloc --include-lang=md docs

  format:
    cmds:
      - $GOFMT -w pkg/**/*.go
      - $GOFMT -w examples/*/*.go
      - $GOFMT -w tools/debugger/*.go
      - goimports -w -local pkg/**/*.go
      - goimports -w -local tools/**/*.go

  lint:
    cmds:
      - task: lint-go
      - task: lint-md
      # https://github.com/markdownlint/markdownlint/issues/136
      - |
        if grep -q "]()" docs/*.md; then
          echo "Error: Empty links" >&2
          exit 1
        fi
      - task: check-fmt

  lint-go:
    cmds:
      - golangci-lint run

  lint-md:
    cmds:
      - mdl -g -c .mdlrc .

  check-fmt:
    silent: false
    cmds:
      - test -z $($GOFMT -l pkg/**/*.go)
      - test -z $($GOFMT -l examples/*/*.go)
      - test -z $($GOFMT -l tools/debugger/*.go)
      - test -z $(goimports -l -local pkg/**/*.go)
      - test -z $(goimports -l -local tools/**/*.go)

  changelog:
    cmds:
      - github_changelog_generator
      - head -n -4 CHANGELOG.md > CHANGELOG-tmp.md
      - mv CHANGELOG-tmp.md CHANGELOG.md

  install-deps:
    cmds:
      - go mod tidy
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      - go install mvdan.cc/gofumpt@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - gem install mdl
      - gem install github_changelog_generator