version: '3'

dotenv: ['.env']

env:
  GOFMT: gofumpt

tasks:

  build-machine:
    cmds:
      - go build pkg/machine/*.go

  build-telemetry:
    cmds:
      - go build pkg/telemetry/*.go

  build-debugger:
    cmds:
      - go build -o build/am-dbg tools/am-dbg/*.go

  build:
    cmds:
      - task: build-machine
      - task: build-telemetry
      - task: build-debugger

  debugger:
    cmds:
      - go run tools/am-dbg/main.go {{.CLI_ARGS}}

  debugger-client:
    cmds:
      - go run tools/am-dbg/main.go 
          --log-machine-id false 
          --log-level 2
          --am-dbg-url localhost:9913

  debugger-debugger:
    cmds:
      - go run tools/am-dbg/main.go 
          --log-file am-dbg-dbg.log 
          --log-machine-id false 
          --log-level 2
          --server-url localhost:9913

  test:
    cmds:
      - task: clean
      - go test ./...

  test-verbose:
    cmds:
      - go test ./... -v

  clean:
    cmds:
      - go clean -testcache

  cloc:
    cmds:
      - gocloc pkg/machine --not-match=_test\.go
      - gocloc pkg/machine/*_test.go
      - gocloc tools/am-dbg/**/* --not-match=_test\.go
      - gocloc examples
      - gocloc --include-lang=md docs

  format:
    cmds:
      - $GOFMT -w examples/*/*.go
      - $GOFMT -w pkg/**/*.go
      - $GOFMT -w tools/**/*.go
      - goimports -w -local "github.com/pancsta/asyncmachine-go" pkg/**/*.go
      - goimports -w -local "github.com/pancsta/asyncmachine-go" tools/**/*.go

  lint:
    cmds:
      - task: lint-go
      - task: lint-md
      # https://github.com/markdownlint/markdownlint/issues/136
      - |
        if grep -q "]()" docs/*.md; then
          echo "Error: Empty links" >&2
          exit 1
        fi
      - task: check-fmt

  lint-go:
    cmds:
      - golangci-lint run --fix

  lint-md:
    cmds:
      - mdl -g -c .mdlrc .

  check-fmt:
    silent: false
    cmds:
      - test -z $($GOFMT -l examples/**/*.go)
      - test -z $($GOFMT -l pkg/**/*.go)
      - test -z $($GOFMT -l tools/am-dbg/*.go)
      - test -z $(goimports -l -local "github.com/pancsta/asyncmachine-go" pkg/**/*.go)
      - test -z $(goimports -l -local "github.com/pancsta/asyncmachine-go" tools/**/*.go)

  changelog:
    cmds:
      - github_changelog_generator
      - head -n -4 CHANGELOG.md > CHANGELOG-tmp.md
      - mv CHANGELOG-tmp.md CHANGELOG.md

  install-deps:
    cmds:
      - go mod tidy
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      - go install mvdan.cc/gofumpt@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      # TODO switch to nodejs md linter
      - gem install mdl
      - gem install github_changelog_generator