// Code generated by am-gen; DO NOT EDIT.
//go:build tinygo

package states

import am "github.com/pancsta/asyncmachine-go/pkg/machine"

// S is a type alias for a list of state names.
type S = am.S

// ///// ///// /////

// ///// TOPIC

// ///// ///// /////

// TopicStatesDef contains states for Topic.
type TopicStatesDef struct {
	*am.StatesBase
	ErrJoining          string
	ErrListening        string
	Joining             string
	Joined              string
	Started             string
	MissPeersByUpdates  string
	MissPeersByGossip   string
	MissUpdatesByGossip string
	SendGossips         string
	SendUpdates         string
	ReqMissingPeers     string
	ReqMissingUpdates   string
	DoSendInfo          string
	PeerJoined          string
	PeerLeft            string
	MsgInfo             string
	MsgBye              string
	MsgUpdates          string
	MsgReqInfo          string
	MsgReqUpdates       string
	MsgReceived         string
	ListMachines        string
	SendMsg             string
	ProcessMsgs         string
	SendInfo            string
	ErrNetwork          string
	ErrHandlerTimeout   string
	Start               string
	Ready               string
	Healthcheck         string
	Heartbeat           string
	ErrConnecting       string
	Connecting          string
	Connected           string
	Disconnecting       string
	Disconnected        string
	RegisterDisposal    string
	Disposing           string
	Disposed            string
}

// TopicGroupsDef contains all the state groups of the Topic state schema.
type TopicGroupsDef struct {
	Connected S
}

// TopicSchema represents all relations and properties of TopicStates.
var TopicSchema = am.Schema{
	ssT.Connected: {
		Remove:  S{ssT.Connecting, ssT.Connected, ssT.Disconnecting, ssT.Disconnected},
		Require: S{ssT.Start},
	},
	ssT.Connecting: {
		Remove:  S{ssT.Connecting, ssT.Connected, ssT.Disconnecting, ssT.Disconnected},
		Require: S{ssT.Start},
	},
	ssT.Disconnected: {
		Auto:   true,
		Remove: S{ssT.Connecting, ssT.Connected, ssT.Disconnecting, ssT.Disconnected},
	},
	ssT.Disconnecting: {Remove: S{ssT.Connecting, ssT.Connected, ssT.Disconnecting, ssT.Disconnected}},
	ssT.Disposed:      {Remove: S{ssT.Disposing, ssT.Start}},
	ssT.Disposing:     {Remove: S{ssT.Start}},
	ssT.DoSendInfo:    {Require: S{ssT.Joined}},
	ssT.ErrConnecting: {Require: S{ssT.Exception}},
	ssT.ErrHandlerTimeout: {
		Add:     S{ssT.Exception},
		Multi:   true,
		Require: S{ssT.Exception},
	},
	ssT.ErrJoining:   {Require: S{ssT.Exception}},
	ssT.ErrListening: {Require: S{ssT.Exception}},
	ssT.ErrNetwork: {
		Add:     S{ssT.Exception},
		Multi:   true,
		Require: S{ssT.Exception},
	},
	ssT.Exception:   {Multi: true},
	ssT.Healthcheck: {Multi: true},
	ssT.Heartbeat:   {Require: S{ssT.Joined}},
	ssT.Joined: {
		Remove:  S{ssT.Joining},
		Require: S{ssT.Connected},
	},
	ssT.Joining: {
		Remove:  S{ssT.Joined},
		Require: S{ssT.Connected},
	},
	ssT.ListMachines: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.MissPeersByGossip: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.MissPeersByUpdates: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.MissUpdatesByGossip: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.MsgBye: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.MsgInfo: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.MsgReceived: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.MsgReqInfo: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.MsgReqUpdates: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.MsgUpdates: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.PeerJoined: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.PeerLeft: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.ProcessMsgs: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.Ready: {
		Auto:    true,
		Require: S{ssT.Joined},
	},
	ssT.RegisterDisposal:  {Multi: true},
	ssT.ReqMissingPeers:   {Require: S{ssT.Joined}},
	ssT.ReqMissingUpdates: {Require: S{ssT.Joined}},
	ssT.SendGossips:       {Require: S{ssT.Joined}},
	ssT.SendInfo:          {Require: S{ssT.Joined}},
	ssT.SendMsg: {
		Multi:   true,
		Require: S{ssT.Joined},
	},
	ssT.SendUpdates: {Require: S{ssT.Joined}},
	ssT.Start:       {},
	ssT.Started:     {Require: S{ssT.Start}},
}

// EXPORTS AND GROUPS
var (
	ssT = TopicStatesDef{
		Connected:           "Connected",
		Connecting:          "Connecting",
		Disconnected:        "Disconnected",
		Disconnecting:       "Disconnecting",
		Disposed:            "Disposed",
		Disposing:           "Disposing",
		DoSendInfo:          "DoSendInfo",
		ErrConnecting:       "ErrConnecting",
		ErrHandlerTimeout:   "ErrHandlerTimeout",
		ErrJoining:          "ErrJoining",
		ErrListening:        "ErrListening",
		ErrNetwork:          "ErrNetwork",
		Healthcheck:         "Healthcheck",
		Heartbeat:           "Heartbeat",
		Joined:              "Joined",
		Joining:             "Joining",
		ListMachines:        "ListMachines",
		MissPeersByGossip:   "MissPeersByGossip",
		MissPeersByUpdates:  "MissPeersByUpdates",
		MissUpdatesByGossip: "MissUpdatesByGossip",
		MsgBye:              "MsgBye",
		MsgInfo:             "MsgInfo",
		MsgReceived:         "MsgReceived",
		MsgReqInfo:          "MsgReqInfo",
		MsgReqUpdates:       "MsgReqUpdates",
		MsgUpdates:          "MsgUpdates",
		PeerJoined:          "PeerJoined",
		PeerLeft:            "PeerLeft",
		ProcessMsgs:         "ProcessMsgs",
		Ready:               "Ready",
		RegisterDisposal:    "RegisterDisposal",
		ReqMissingPeers:     "ReqMissingPeers",
		ReqMissingUpdates:   "ReqMissingUpdates",
		SendGossips:         "SendGossips",
		SendInfo:            "SendInfo",
		SendMsg:             "SendMsg",
		SendUpdates:         "SendUpdates",
		Start:               "Start",
		Started:             "Started",
		StatesBase:          &am.StatesBase{Exception: "Exception"},
	}
	sgT = TopicGroupsDef{Connected: S{ssT.Connecting, ssT.Connected, ssT.Disconnecting, ssT.Disconnected}}

	// TopicStates contains all the states for the Topic state schema.
	TopicStates = ssT

	// TopicGroups contains all the state groups for the Topic state schema.
	TopicGroups = sgT
)

func init() {
	ssT.SetNames(S{"Exception", "ErrJoining", "ErrListening", "Joining", "Joined", "Started", "MissPeersByUpdates", "MissPeersByGossip", "MissUpdatesByGossip", "SendGossips", "SendUpdates", "ReqMissingPeers", "ReqMissingUpdates", "DoSendInfo", "PeerJoined", "PeerLeft", "MsgInfo", "MsgBye", "MsgUpdates", "MsgReqInfo", "MsgReqUpdates", "MsgReceived", "ListMachines", "SendMsg", "ProcessMsgs", "SendInfo", "ErrNetwork", "ErrHandlerTimeout", "Start", "Ready", "Healthcheck", "Heartbeat", "ErrConnecting", "Connecting", "Connected", "Disconnecting", "Disconnected", "RegisterDisposal", "Disposing", "Disposed"})
	groups := map[string][]int{"Connected": {33, 34, 35, 36}}
	ssT.SetStateGroups(groups, []string{"Connected"})
}
