// Code generated by am-gen; DO NOT EDIT.
//go:build tinygo

package node

import am "github.com/pancsta/asyncmachine-go/pkg/machine"

func ClientNegotiations(h *Client) map[string]am.HandlerNegotiation {
	return map[string]am.HandlerNegotiation{
		"ServerPayloadEnter":   h.ServerPayloadEnter,
		"StartEnter":           h.StartEnter,
		"WorkerRequestedEnter": h.WorkerRequestedEnter,
	}
}

func ClientFinals(h *Client) map[string]am.HandlerFinal {
	return map[string]am.HandlerFinal{
		"ExceptionState":       h.ExceptionState,
		"ServerPayloadState":   h.ServerPayloadState,
		"StartEnd":             h.StartEnd,
		"StartState":           h.StartState,
		"WorkerRequestedState": h.WorkerRequestedState,
	}
}
func SupervisorNegotiations(h *Supervisor) map[string]am.HandlerNegotiation {
	return map[string]am.HandlerNegotiation{
		"ClientDisconnectedEnter": h.ClientDisconnectedEnter,
		"ForkWorkerEnter":         h.ForkWorkerEnter,
		"ForkingWorkerEnter":      h.ForkingWorkerEnter,
		"KillingWorkerEnter":      h.KillingWorkerEnter,
		"ListWorkersEnter":        h.ListWorkersEnter,
		"PoolReadyEnter":          h.PoolReadyEnter,
		"PoolReadyExit":           h.PoolReadyExit,
		"ProvideWorkerEnter":      h.ProvideWorkerEnter,
		"SetWorkerEnter":          h.SetWorkerEnter,
		"StartEnter":              h.StartEnter,
		"WorkerConnectedEnter":    h.WorkerConnectedEnter,
		"WorkerForkedEnter":       h.WorkerForkedEnter,
		"WorkerKilledEnter":       h.WorkerKilledEnter,
	}
}

func SupervisorFinals(h *Supervisor) map[string]am.HandlerFinal {
	return map[string]am.HandlerFinal{
		"ClientConnectedState":    h.ClientConnectedState,
		"ClientDisconnectedState": h.ClientDisconnectedState,
		"ClientSendPayloadState":  h.ClientSendPayloadState,
		"ErrWorkerState":          h.ErrWorkerState,
		"ExceptionState":          h.ExceptionState,
		"ForkWorkerState":         h.ForkWorkerState,
		"ForkingWorkerState":      h.ForkingWorkerState,
		"HealthcheckState":        h.HealthcheckState,
		"HeartbeatState":          h.HeartbeatState,
		"KillWorkerState":         h.KillWorkerState,
		"KillingWorkerState":      h.KillingWorkerState,
		"ListWorkersState":        h.ListWorkersState,
		"NormalizingPoolState":    h.NormalizingPoolState,
		"ProvideWorkerState":      h.ProvideWorkerState,
		"SetWorkerState":          h.SetWorkerState,
		"StartEnd":                h.StartEnd,
		"StartState":              h.StartState,
		"SuperSendPayloadState":   h.SuperSendPayloadState,
		"WorkerConnectedState":    h.WorkerConnectedState,
		"WorkerForkedState":       h.WorkerForkedState,
		"WorkerGoneState":         h.WorkerGoneState,
		"WorkerKilledState":       h.WorkerKilledState,
		"WorkerReadyState":        h.WorkerReadyState,
	}
}
func WorkerNegotiations(h *Worker) map[string]am.HandlerNegotiation {
	return map[string]am.HandlerNegotiation{
		"SendPayloadEnter": h.SendPayloadEnter,
		"ServeClientEnter": h.ServeClientEnter,
		"StartEnter":       h.StartEnter,
	}
}

func WorkerFinals(h *Worker) map[string]am.HandlerFinal {
	return map[string]am.HandlerFinal{
		"ErrNetworkState":     h.ErrNetworkState,
		"ExceptionState":      h.ExceptionState,
		"HealthcheckState":    h.HealthcheckState,
		"LocalRpcReadyState":  h.LocalRpcReadyState,
		"PublicRpcReadyState": h.PublicRpcReadyState,
		"RpcReadyState":       h.RpcReadyState,
		"ServeClientState":    h.ServeClientState,
		"StartEnd":            h.StartEnd,
		"StartState":          h.StartState,
	}
}
func BootstrapNegotiations(h *Bootstrap) map[string]am.HandlerNegotiation {
	return map[string]am.HandlerNegotiation{"WorkerAddrEnter": h.WorkerAddrEnter}
}

func BootstrapFinals(h *Bootstrap) map[string]am.HandlerFinal {
	return map[string]am.HandlerFinal{
		"ExceptionState":  h.ExceptionState,
		"StartEnd":        h.StartEnd,
		"StartState":      h.StartState,
		"WorkerAddrState": h.WorkerAddrState,
	}
}

// ArgsRpcToArgs copies identical fields from [ARpc] to [A].
func ArgsRpcToArgs(argsRpc *ARpc) A {
	return A{
		Addr:      argsRpc.Addr,
		Dispose:   argsRpc.Dispose,
		Err:       argsRpc.Err,
		Id:        argsRpc.Id,
		MachTick:  argsRpc.MachTick,
		MachTime:  argsRpc.MachTime,
		Method:    argsRpc.Method,
		Name:      argsRpc.Name,
		Payload:   argsRpc.Payload,
		QueueTick: argsRpc.QueueTick,
		StartedAt: argsRpc.StartedAt,
	}
}

// ArgsToArgsRpc copies identical fields from [A] to [ARpc].
func ArgsToArgsRpc(args *A) ARpc {
	return ARpc{
		Addr:      args.Addr,
		Client:    args.Client,
		Dispose:   args.Dispose,
		Err:       args.Err,
		Id:        args.Id,
		MachTick:  args.MachTick,
		MachTime:  args.MachTime,
		Method:    args.Method,
		Name:      args.Name,
		Payload:   args.Payload,
		QueueTick: args.QueueTick,
		StartedAt: args.StartedAt,
	}
}
