// Code generated by am-gen; DO NOT EDIT.
//go:build tinygo

package rpc

import am "github.com/pancsta/asyncmachine-go/pkg/machine"

func ClientNegotiations(h *Client) map[string]am.HandlerNegotiation {
	return map[string]am.HandlerNegotiation{
		"ConnectingEnter":    h.ConnectingEnter,
		"DisconnectedEnter":  h.DisconnectedEnter,
		"DisconnectingEnter": h.DisconnectingEnter,
		"ExceptionEnter":     h.ExceptionEnter,
		"HandshakeDoneEnter": h.HandshakeDoneEnter,
		"RetryingCallEnter":  h.RetryingCallEnter,
		"ServerPayloadEnter": h.ServerPayloadEnter,
	}
}

func ClientFinals(h *Client) map[string]am.HandlerFinal {
	return map[string]am.HandlerFinal{
		"CallRetryFailedState": h.CallRetryFailedState,
		"ConnectedState":       h.ConnectedState,
		"ConnectingState":      h.ConnectingState,
		"DisconnectedState":    h.DisconnectedState,
		"DisconnectingState":   h.DisconnectingState,
		"ExceptionState":       h.ExceptionState,
		"HandshakeDoneState":   h.HandshakeDoneState,
		"HandshakingState":     h.HandshakingState,
		"HealthcheckState":     h.HealthcheckState,
		"RetryingConnState":    h.RetryingConnState,
		"ServerPayloadState":   h.ServerPayloadState,
		"StartEnd":             h.StartEnd,
		"StartState":           h.StartState,
	}
}
func ServerNegotiations(h *Server) map[string]am.HandlerNegotiation {
	return map[string]am.HandlerNegotiation{
		"ExceptionEnter":    h.ExceptionEnter,
		"RpcAcceptingEnter": h.RpcAcceptingEnter,
		"RpcReadyEnter":     h.RpcReadyEnter,
		"RpcStartingEnter":  h.RpcStartingEnter,
	}
}

func ServerFinals(h *Server) map[string]am.HandlerFinal {
	return map[string]am.HandlerFinal{
		"ExceptionState":    h.ExceptionState,
		"HandshakeDoneEnd":  h.HandshakeDoneEnd,
		"RpcAcceptingState": h.RpcAcceptingState,
		"RpcReadyState":     h.RpcReadyState,
		"RpcStartingState":  h.RpcStartingState,
		"StartEnd":          h.StartEnd,
		"StartState":        h.StartState,
	}
}

// ArgsRpcToArgs copies identical fields from [ARpc] to [A].
func ArgsRpcToArgs(argsRpc *ARpc) A {
	return A{
		Addr:      argsRpc.Addr,
		Dispose:   argsRpc.Dispose,
		Err:       argsRpc.Err,
		Id:        argsRpc.Id,
		MachTick:  argsRpc.MachTick,
		MachTime:  argsRpc.MachTime,
		Method:    argsRpc.Method,
		Name:      argsRpc.Name,
		Payload:   argsRpc.Payload,
		QueueTick: argsRpc.QueueTick,
		StartedAt: argsRpc.StartedAt,
	}
}

// ArgsToArgsRpc copies identical fields from [A] to [ARpc].
func ArgsToArgsRpc(args *A) ARpc {
	return ARpc{
		Addr:      args.Addr,
		Client:    args.Client,
		Dispose:   args.Dispose,
		Err:       args.Err,
		Id:        args.Id,
		MachTick:  args.MachTick,
		MachTime:  args.MachTime,
		Method:    args.Method,
		Name:      args.Name,
		Payload:   args.Payload,
		QueueTick: args.QueueTick,
		StartedAt: args.StartedAt,
	}
}
