direction: right

classes: {
  link-rel: {
    style: {
      stroke-dash: 3
    }
  }
  link-handler:{
    style: {
      stroke-dash: 3
    }
  }
  link-sync: {
    style: {
      stroke: yellow
      stroke-dash: 3
    }
  }
  state: {
    style: {
      stroke: white
      border-radius: 999
      fill: "#45475A"
      font-size: 20
    }
  }
  mach: {
    style: {
      stroke: "#5F5C5C"
      fill: "#262424"
      font-size: 30
    }
  }
  host: {
    style: {
      stroke: "#5F5C5C"
      fill: "#302E2E"
      font-size: 30
    }
  }
  handler: {
    style: {
      fill: "black"
    }
  }
  struct: {
    style: {
      fill: "#262424"
      font-size: 30
    }
  }
  transparent: {
    style: {
      opacity: 0
    }
  }
  sequence: {
    style: {
     font-size: 16
     stroke: "#7E7878"
   }
  }
}

title: |md
  # aRPC handler mutations
| {near: top-center}

"" {
  h1: Host 1 {
    s: Net Source Mach {
      Foo: Foo: 5
      Bar: Bar: 0

      Foo.class: state
      Bar.class: state
    }
    s.class: mach
  }
  h1.class: host
  h1.s -> h2.nm: aRPC sync:\n- state names\n- schema\n- machine time

  h2: Host 2 {
    nm: Net Mach {
      explanation: |md
        - full schema
        - relation-based negotiation
        - no handler loop
      |
      Foo: Foo: 5
      Bar: Bar: 0

      Foo.class: state
      Bar.class: state
    }
    nm.class: mach

    nhm: Net Handler Mach {
      explanation: |md
        - no schema
          - only state names with clock values
        - no mutations
        - handler loop
      |

      Foo: Foo: 5
      Bar: Bar: 0

      Foo.class: state
      Bar.class: state

    }
    nhm.class: mach
    nm -> nhm: Pipe Any

    h: Handlers {
      Handler: FooState()
      Handler.class: handler
    }
    h.class: struct
    nhm.Foo -> h.Handler: {class: link-handler}
  }
  h2.class: host
  h2.h.Handler -> h1.s.Bar: Indirect Add {class: link-sync}
}
"".class: transparent

# ##### ##### #####

# ##### SEQUENCE

# ##### ##### #####

Events\: local Foo handler adds remote Bar: {
  shape: sequence_diagram

  nmf: Net Mach - Foo
  nmf.class: [mach; sequence]
  nhf: Net Handler Mach - Foo
  nhf.class: [mach; sequence]
  lh: Local Handler
  lh.class: [handler; sequence]
  nmb: Net Mach - Bar
  nmb.class: [mach; sequence]
  rc: RPC client
  rc.class: [host; sequence]
  nsb: Net Source - Bar
  nsb.class: [mach; sequence]

  nmf -> nhf: Piped Add
  nhf -> lh: Handler Loop
  lh -> nmb: Add (negotiation)
  nmb -> rc: Fwd Add
  rc -> nsb: Push Add
}
