flowchart TB

    subgraph ClientHost [Client Host]
        subgraph Consumer
            con-MethodOrHandler["MethodOrHandler()"]
            con-WorkerPayload(["WorkerPayload"])
        end

        subgraph RemoteWorkerMach [Remote Worker Mach]
        %% Provide Worker is requested to provide some (named) data.
            rw-Provide([ProvideABC])
        end

        subgraph RPCClientMach [RPC Client Mach]
            c-WorkerPayload([WorkerPayload])
            c-RemoteSendPayload["RemoteSendPayload()"]
            c-WorkerPayloadState["WorkerPayloadState()"]
        end
    end

    subgraph ServerHost [Server Host]
        subgraph RPCServer [RPC Server]
            srv-SendPayloadState["SendPayloadState()"]
        end

        subgraph SourceWorkerMach [Source Worker Mach]
        %% Provide Worker is requested to provide some (named) data.
            sw-Provide([ProvideABC])
            sw-ProvideState["ProvideABCState()"]
            sw-SendPayload(["SendPayload"])
        end
    end

    %% steps
    con-MethodOrHandler -- Add --> rw-Provide
    rw-Provide -- Add --> sw-Provide
    sw-Provide == handle ==> sw-ProvideState
    sw-ProvideState -- Add --> sw-SendPayload
    sw-SendPayload == handle ==> srv-SendPayloadState
    srv-SendPayloadState -. call .-> c-RemoteSendPayload
    c-RemoteSendPayload -- Add --> c-WorkerPayload
    c-WorkerPayload == handle ==> c-WorkerPayloadState
    c-WorkerPayloadState -- Add --> con-WorkerPayload
