{
 "title": "Machine Dashboard: $IDS",
 "description": "AsyncMachine internals gathered by pkg/telemetry",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Machine: $IDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transition changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "mach_$IDS_queue_size", "legendFormat": "Queue size", "query": "mach_$IDS_queue_size" },
    { "expr": "mach_$IDS_tx_tick", "legendFormat": "Tx ticks", "query": "mach_$IDS_tx_tick" },
    { "expr": "mach_$IDS_steps_amount", "legendFormat": "Number of tx steps", "query": "mach_$IDS_steps_amount" },
    { "expr": "mach_$IDS_handlers_amount", "legendFormat": "Called handlers", "query": "mach_$IDS_handlers_amount" },
    { "expr": "mach_$IDS_states_added", "legendFormat": "States added", "query": "mach_$IDS_states_added" },
    { "expr": "mach_$IDS_states_removed", "legendFormat": "States removed", "query": "mach_$IDS_states_removed" },
    { "expr": "mach_$IDS_touched", "legendFormat": "States touched", "query": "mach_$IDS_touched" }
   ]
  },
  {
   "title": "Machine states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "mach_$IDS_ref_states_amount", "legendFormat": "States referenced in relations", "query": "mach_$IDS_ref_states_amount" },
    { "expr": "mach_$IDS_relations_amount", "legendFormat": "Relations", "query": "mach_$IDS_relations_amount" },
    { "expr": "mach_$IDS_states_active_amount", "legendFormat": "States active", "query": "mach_$IDS_states_active_amount" },
    {
     "expr": "mach_$IDS_states_inactive_amount",
     "legendFormat": "States inactive",
     "query": "mach_$IDS_states_inactive_amount"
    }
   ]
  },
  {
   "title": "Transition time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "mach_$IDS_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_$IDS_tx_time / 1000" }
   ]
  },
  {
   "title": "Average transition time",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "mach_$IDS_tx_time / 1000", "legendFormat": "Tx time (ms)", "query": "mach_$IDS_tx_time / 1000" }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "mach_$IDS_exceptions_count", "legendFormat": "Exceptions", "query": "mach_$IDS_exceptions_count" }
   ]
  }
 ]
}