// Code generated by am-gen; DO NOT EDIT.
//go:build tinygo

package pubsub

import am "github.com/pancsta/asyncmachine-go/pkg/machine"

func TopicNegotiations(h *Topic) map[string]am.HandlerNegotiation {
	return map[string]am.HandlerNegotiation{
		"ConnectingEnter":          h.ConnectingEnter,
		"DoSendInfoEnter":          h.DoSendInfoEnter,
		"ExceptionEnter":           h.ExceptionEnter,
		"ListMachinesEnter":        h.ListMachinesEnter,
		"MissPeersByGossipEnter":   h.MissPeersByGossipEnter,
		"MissPeersByGossipExit":    h.MissPeersByGossipExit,
		"MissPeersByUpdatesEnter":  h.MissPeersByUpdatesEnter,
		"MissPeersByUpdatesExit":   h.MissPeersByUpdatesExit,
		"MissUpdatesByGossipEnter": h.MissUpdatesByGossipEnter,
		"MissUpdatesByGossipExit":  h.MissUpdatesByGossipExit,
		"MsgByeEnter":              h.MsgByeEnter,
		"MsgInfoEnter":             h.MsgInfoEnter,
		"MsgReceivedEnter":         h.MsgReceivedEnter,
		"MsgReqInfoEnter":          h.MsgReqInfoEnter,
		"MsgReqUpdatesEnter":       h.MsgReqUpdatesEnter,
		"MsgUpdatesEnter":          h.MsgUpdatesEnter,
		"PeerJoinedEnter":          h.PeerJoinedEnter,
		"PeerLeftEnter":            h.PeerLeftEnter,
		"ReadyEnter":               h.ReadyEnter,
		"ReqMissingPeersEnter":     h.ReqMissingPeersEnter,
		"ReqMissingUpdatesEnter":   h.ReqMissingUpdatesEnter,
		"SendGossipsEnter":         h.SendGossipsEnter,
		"SendInfoEnter":            h.SendInfoEnter,
		"SendMsgEnter":             h.SendMsgEnter,
		"SendUpdatesEnter":         h.SendUpdatesEnter,
		"StartEnter":               h.StartEnter,
	}
}

func TopicFinals(h *Topic) map[string]am.HandlerFinal {
	return map[string]am.HandlerFinal{
		"ConnectingState":          h.ConnectingState,
		"DoSendInfoState":          h.DoSendInfoState,
		"ExceptionState":           h.ExceptionState,
		"HeartbeatState":           h.HeartbeatState,
		"JoinedEnd":                h.JoinedEnd,
		"JoinedState":              h.JoinedState,
		"JoiningState":             h.JoiningState,
		"ListMachinesState":        h.ListMachinesState,
		"MissPeersByGossipState":   h.MissPeersByGossipState,
		"MissPeersByUpdatesState":  h.MissPeersByUpdatesState,
		"MissUpdatesByGossipState": h.MissUpdatesByGossipState,
		"MsgInfoState":             h.MsgInfoState,
		"MsgReqInfoState":          h.MsgReqInfoState,
		"MsgReqUpdatesState":       h.MsgReqUpdatesState,
		"MsgUpdatesState":          h.MsgUpdatesState,
		"PeerJoinedState":          h.PeerJoinedState,
		"ProcessMsgsState":         h.ProcessMsgsState,
		"ReqMissingPeersState":     h.ReqMissingPeersState,
		"ReqMissingUpdatesState":   h.ReqMissingUpdatesState,
		"SendGossipsState":         h.SendGossipsState,
		"SendInfoState":            h.SendInfoState,
		"SendMsgState":             h.SendMsgState,
		"SendUpdatesState":         h.SendUpdatesState,
		"StartEnd":                 h.StartEnd,
		"StartState":               h.StartState,
	}
}

// ArgsRpcToArgs copies identical fields from [ARpc] to [A].
func ArgsRpcToArgs(argsRpc *ARpc) A {
	return A{
		Addr:      argsRpc.Addr,
		Dispose:   argsRpc.Dispose,
		Err:       argsRpc.Err,
		Id:        argsRpc.Id,
		MachTick:  argsRpc.MachTick,
		MachTime:  argsRpc.MachTime,
		Method:    argsRpc.Method,
		Name:      argsRpc.Name,
		Payload:   argsRpc.Payload,
		QueueTick: argsRpc.QueueTick,
		StartedAt: argsRpc.StartedAt,
	}
}

// ArgsToArgsRpc copies identical fields from [A] to [ARpc].
func ArgsToArgsRpc(args *A) ARpc {
	return ARpc{
		Addr:      args.Addr,
		Client:    args.Client,
		Dispose:   args.Dispose,
		Err:       args.Err,
		Id:        args.Id,
		MachTick:  args.MachTick,
		MachTime:  args.MachTime,
		Method:    args.Method,
		Name:      args.Name,
		Payload:   args.Payload,
		QueueTick: args.QueueTick,
		StartedAt: args.StartedAt,
	}
}
