package generator

import (
	"fmt"
	"os"
	"reflect"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"unicode"

	"github.com/dave/jennifer/jen"

	am "github.com/pancsta/asyncmachine-go/pkg/machine"
)

type S = am.S

func WriteSchemaV3(schema string) error {
	path := strings.Split(os.Getenv("GOPACKAGE"), "/")
	name := path[len(path)-1] + ".gen.go"
	return os.WriteFile(name, []byte(schema), 0644)
}

type SchemaV3 struct {
	ExportName string
	States     am.States
	Schema     am.Schema
	Groups     any
}

// GenSchemaV3 generates a status v1 schema from an initialized v2 schema.
func GenSchemaV3(schemas []SchemaV3) string {
	// gen intro
	f := jen.NewFile("states")

	// Add the build tag at the very top of the file
	f.HeaderComment("Code generated by am-gen; DO NOT EDIT.")
	f.HeaderComment("//go:build tinygo")

	amPath := "github.com/pancsta/asyncmachine-go/pkg/machine"
	f.ImportAlias(amPath, "am")

	// type S = am.S
	f.Comment("S is a type alias for a list of state names.")
	f.Type().Id("S").Op("=").Qual(amPath, "S")

	f.Line()

	suffixes := []string{}

	for _, input := range schemas {
		exportName := input.ExportName
		states := input.States
		schema := input.Schema
		groups := input.Groups
		suffixStart := ToSuffix(exportName)
		suffix := suffixStart
		i := 2
		for slices.Contains(suffixes, suffix) {
			suffix = suffixStart + strconv.Itoa(i)
			i++
		}
		suffixes = append(suffixes, suffix)

		// definitions
		genStatesDef := []jen.Code{}
		genGroupsDef := []jen.Code{}
		genSchema := jen.Dict{}

		// exports
		genStatesInit := jen.Dict{}
		genGroupsInit := jen.Dict{}

		// values init()
		genStateNames := []jen.Code{}
		genGroupsMap := jen.Dict{}
		genGroupsNames := []jen.Code{}

		// states and schema

		for _, name := range states.Names() {
			genStateNames = append(genStateNames, jen.Lit(name))
			if name != am.StateException {
				genStatesDef = append(genStatesDef, jen.Id(name).String())
				genStatesInit[jen.Id(name)] = jen.Lit(name)
			}

			gen := jen.Dict{}
			state := schema[name]
			if state.Auto {
				gen[jen.Id("Auto")] = jen.Lit(true)
			}
			if state.Multi {
				gen[jen.Id("Multi")] = jen.Lit(true)
			}
			if state.Add != nil {
				genRels := []jen.Code{}
				for _, rel := range state.Add {
					if slices.Contains(states.Names(), rel) {
						genRels = append(genRels, jen.Id("ss"+suffix).Dot(rel))

						// dynamic binding
					} else {
						genRels = append(genRels, jen.Lit(rel))
					}
				}
				gen[jen.Id("Add")] = jen.Id("S").Values(genRels...)
			}
			if state.Require != nil {
				genRels := []jen.Code{}
				for _, rel := range state.Require {
					if slices.Contains(states.Names(), rel) {
						genRels = append(genRels, jen.Id("ss"+suffix).Dot(rel))

						// dynamic binding
					} else {
						genRels = append(genRels, jen.Lit(rel))
					}
				}
				gen[jen.Id("Require")] = jen.Id("S").Values(genRels...)
			}
			if state.Remove != nil {
				genRels := []jen.Code{}
				for _, rel := range state.Remove {
					if slices.Contains(states.Names(), rel) {
						genRels = append(genRels, jen.Id("ss"+suffix).Dot(rel))

						// dynamic binding
					} else {
						genRels = append(genRels, jen.Lit(rel))
					}
				}
				gen[jen.Id("Remove")] = jen.Id("S").Values(genRels...)
			}
			if state.After != nil {
				genRels := []jen.Code{}
				for _, rel := range state.After {
					if slices.Contains(states.Names(), rel) {
						genRels = append(genRels, jen.Id("ss"+suffix).Dot(rel))

						// dynamic binding
					} else {
						genRels = append(genRels, jen.Lit(rel))
					}
				}
				gen[jen.Id("After")] = jen.Id("S").Values(genRels...)
			}

			genSchema[jen.Id("ss"+suffix).Dot(name)] = jen.Values(gen)
		}

		// groups

		exGroups := ExtractGroups(groups)
		for name, gStates := range exGroups {
			genGroupsDef = append(genGroupsDef, jen.Id(name).Id("S"))
			genInit := []jen.Code{}
			for _, state := range gStates {
				genInit = append(genInit, jen.Id("ss"+suffix).Dot(state))
			}
			genMap := []jen.Code{}
			for _, state := range gStates {
				genMap = append(genMap, jen.Lit(slices.Index(states.Names(), state)))
			}
			genGroupsInit[jen.Id(name)] = jen.Id("S").Values(genInit...)
			genGroupsMap[jen.Lit(name)] = jen.Values(genMap...)
			genGroupsNames = append(genGroupsNames, jen.Lit(name))
		}

		// GENERATE
		f.Comment("// ///// ///// /////")
		f.Line()
		f.Comment("// ///// " + strings.ToUpper(spaceCase(exportName)))
		f.Line()
		f.Comment("// ///// ///// /////")
		f.Line()

		// type FileStatesDef struct { ... }
		f.Comment(exportName + "StatesDef contains states for " + exportName + ".")
		genStatesDef = slices.Concat([]jen.Code{jen.Op("*").Qual(amPath, "StatesBase")}, genStatesDef)
		f.Type().Id(exportName + "StatesDef").Struct(genStatesDef...)

		f.Line()

		// type FileGroupsDef struct { ... }
		f.Comment(exportName + "GroupsDef contains all the state groups of the " + exportName + " state schema.")
		f.Type().Id(exportName + "GroupsDef").Struct(genGroupsDef...)

		f.Line()

		// var FileSchema = am.Schema{ ... }
		f.Comment(exportName + "Schema represents all relations and properties of " + exportName + "States.")
		f.Var().Id(exportName+"Schema").Op("=").Qual(amPath, "Schema").Values(genSchema)

		f.Line()

		// exports
		f.Comment("EXPORTS AND GROUPS")
		genStatesInit[jen.Id("StatesBase")] = jen.Op("&").Qual(amPath, "StatesBase").Values(jen.Dict{
			jen.Id("Exception"): jen.Lit("Exception")})
		f.Var().Defs(
			jen.Id("ss"+suffix).Op("=").Id(exportName+"StatesDef").Values(genStatesInit),
			jen.Id("sg"+suffix).Op("=").Id(exportName+"GroupsDef").Values(genGroupsInit),
			jen.Line(),
			jen.Comment(exportName+"States contains all the states for the "+exportName+" state schema."),
			jen.Id(exportName+"States").Op("=").Id("ss"+suffix),
			jen.Line(),
			jen.Comment(exportName+"Groups contains all the state groups for the "+exportName+" state schema."),
			jen.Id(exportName+"Groups").Op("=").Id("sg"+suffix),
		)

		f.Line()

		// func init() { ... }
		f.Func().Id("init").Params().Block(
			// Note: I preserved your exact string values here, even though they contain
			// "CreatingExpense" etc. from the previous schema instance.
			jen.Id("ss"+suffix).Dot("SetNames").Call(jen.Id("S").Values(genStateNames...)),
			jen.Id("groups").Op(":=").Map(jen.String()).Index().Int().Values(genGroupsMap),
			jen.Id("ss"+suffix).Dot("SetStateGroups").Call(
				jen.Id("groups"),
				jen.Index().String().Values(genGroupsNames...),
			),
		)
	}

	// combine
	return fmt.Sprintf("%#v", f)
}

// ExtractGroups takes any struct and recursively extracts []string fields.
func ExtractGroups(obj any) map[string]S {
	result := make(map[string]S)

	// Start the recursive extraction
	extract(reflect.ValueOf(obj), result)

	return result
}

func extract(v reflect.Value, result map[string]S) {
	// 1. Dereference pointers and interfaces to get to the underlying value
	for v.Kind() == reflect.Ptr || v.Kind() == reflect.Interface {
		if v.IsNil() {
			return // Skip nil pointers entirely to avoid panics
		}
		v = v.Elem()
	}

	// 2. We only care about traversing structs
	if v.Kind() != reflect.Struct {
		return
	}

	t := v.Type()

	// 3. Iterate through all fields of the struct
	for i := 0; i < v.NumField(); i++ {
		fieldVal := v.Field(i)
		fieldType := t.Field(i)

		// Skip unexported fields (lowercase names) as they cannot be accessed
		if !fieldVal.CanInterface() {
			continue
		}

		// Dereference field if it's a pointer to check its underlying type
		valToInspect := fieldVal
		for valToInspect.Kind() == reflect.Ptr || valToInspect.Kind() == reflect.Interface {
			if valToInspect.IsNil() {
				break
			}
			valToInspect = valToInspect.Elem()
		}

		if !valToInspect.IsValid() {
			continue
		}

		// 4. If the field is a struct itself, recurse into it
		if valToInspect.Kind() == reflect.Struct {
			extract(valToInspect, result)
			continue
		}

		// 5. If it's not a struct, check if it is exactly a []string
		if slice, ok := valToInspect.Interface().(S); ok {
			result[fieldType.Name] = slice
		}
	}
}

// ///// ///// /////

// ///// HANDLERS

// ///// ///// /////

func WriteHandlers(schema string) error {
	path := strings.Split(os.Getenv("GOPACKAGE"), "/")
	name := path[len(path)-1] + ".gen.go"
	return os.WriteFile(name, []byte(schema), 0644)
}

type Handlers struct {
	States   S
	Handlers any
}

type Args struct {
	Id     string
	IdRpc  string
	Val    any
	ValRpc any
}

func GenHandlers(pkg string, args *Args, handlers ...Handlers) string {
	// header

	if pkg == "" {
		pkg = os.Getenv("GOPACKAGE")
	}

	f := jen.NewFile(pkg)
	f.HeaderComment("Code generated by am-gen; DO NOT EDIT.")
	f.HeaderComment("//go:build tinygo")

	amPath := "github.com/pancsta/asyncmachine-go/pkg/machine"
	f.ImportAlias(amPath, "am")

	// handlers

	for _, h := range handlers {

		states := h.States

		v := reflect.ValueOf(h.Handlers)
		if v.Kind() != reflect.Ptr || v.Elem().Kind() != reflect.Struct {
			panic("GenHandlers expects a pointer to a struct")
		}

		name := reflect.TypeOf(h.Handlers).Elem().Name()
		negs := jen.Dict{}
		finals := jen.Dict{}
		methods, err := am.ListHandlers(h.Handlers, states)
		if err != nil {
			panic(err)
		}

		for _, name := range methods {
			isFinal := strings.HasSuffix(name, am.SuffixState) ||
				strings.HasSuffix(name, am.SuffixEnd)
			if isFinal {
				finals[jen.Lit(name)] = jen.Id("h").Dot(name)
			} else {
				negs[jen.Lit(name)] = jen.Id("h").Dot(name)
			}
		}

		// func MachineHandlersNegotiations(h *MachineHandlers) map[string]am.HandlerNegotiation { ... }
		f.Func().Id(name+"Negotiations").
			Params(jen.Id("h").Op("*").Id(name)).
			Map(jen.String()).Qual(amPath, "HandlerNegotiation").
			Block(
				jen.Return(
					jen.Map(jen.String()).Qual(amPath, "HandlerNegotiation").Values(negs),
				),
			)

		f.Line()

		// func MachineHandlersFinals(h *MachineHandlers) map[string]am.HandlerFinal { ... }
		f.Func().Id(name+"Finals").
			Params(jen.Id("h").Op("*").Id(name)).
			Map(jen.String()).Qual(amPath, "HandlerFinal").
			Block(
				jen.Return(
					jen.Map(jen.String()).Qual(amPath, "HandlerFinal").Values(finals),
				),
			)
	}

	if args != nil {
		GenArgsToArgs(f, args)
	}

	// Output the generated code
	return fmt.Sprintf("%#v", f)
}

func GenArgsToArgs(f *jen.File, args *Args) {
	// RPC to Args
	dict := jen.Dict{}
	for _, field := range ExportedFields(args.ValRpc) {
		dict[jen.Id(field)] = jen.Id("argsRpc").Dot(field)
	}

	f.Comment("ArgsRpcToArgs copies identical fields from [" +
		args.IdRpc + "] to [" + args.Id + "].")
	f.Func().Id("ArgsRpcToArgs").
		Params(jen.Id("argsRpc").Op("*").Id(args.IdRpc)).
		Id(args.Id).
		Block(
			jen.Return(
				jen.Id(args.Id).Values(dict),
			),
		)

	// Args to RPC
	dict = jen.Dict{}
	for _, field := range ExportedFields(args.Val) {
		dict[jen.Id(field)] = jen.Id("args").Dot(field)
	}

	f.Comment("ArgsToArgsRpc copies identical fields from [" +
		args.Id + "] to [" + args.IdRpc + "].")
	f.Func().Id("ArgsToArgsRpc").
		Params(jen.Id("args").Op("*").Id(args.Id)).
		Id(args.IdRpc).
		Block(
			jen.Return(
				jen.Id(args.IdRpc).Values(dict),
			),
		)
}

// ///// ///// /////

// ///// UTILS

// ///// ///// /////

// ExportedFields returns a slice of exported field names for a given struct.
func ExportedFields(obj interface{}) []string {
	var fieldNames []string

	// 1. Get the type of the interface
	t := reflect.TypeOf(obj)

	// 2. If it's a pointer, dereference it to get the underlying type
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}

	// 3. Make sure we are actually dealing with a struct
	if t.Kind() != reflect.Struct {
		return fieldNames // Return empty slice if not a struct
	}

	// 4. Iterate over all fields in the struct type
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)

		// 5. Skip unexported fields (lowercase) because a generated
		// mapper usually can't (and shouldn't) access them.
		if !field.IsExported() {
			continue
		}

		fieldNames = append(fieldNames, field.Name)
	}

	return fieldNames
}

func ToSuffix(s string) string {
	var builder strings.Builder

	for _, r := range s {
		if unicode.IsUpper(r) {
			builder.WriteRune(r) // Keep it uppercase
		}
	}

	return builder.String()
}

var camelCaseRe = regexp.MustCompile(`([a-z0-9])([A-Z])`)

func spaceCase(s string) string {
	// Insert a space between lowercase/number and uppercase letters
	spaced := camelCaseRe.ReplaceAllString(s, "$1 $2")

	// Convert the entire result to lowercase
	return strings.ToLower(spaced)
}
