// Code generated by 'yaegi extract github.com/pancsta/asyncmachine-go/pkg/states/pipes'. DO NOT EDIT.

package symbols

import (
	"github.com/pancsta/asyncmachine-go/pkg/states/pipes"
	"reflect"
)

func init() {
	Symbols["github.com/pancsta/asyncmachine-go/pkg/states/pipes/pipes"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Add":           reflect.ValueOf(pipes.Add),
		"AddFlat":       reflect.ValueOf(pipes.AddFlat),
		"Bind":          reflect.ValueOf(pipes.Bind),
		"BindAny":       reflect.ValueOf(pipes.BindAny),
		"BindConnected": reflect.ValueOf(pipes.BindConnected),
		"BindErr":       reflect.ValueOf(pipes.BindErr),
		"BindMany":      reflect.ValueOf(pipes.BindMany),
		"BindReady":     reflect.ValueOf(pipes.BindReady),
		"BindStart":     reflect.ValueOf(pipes.BindStart),
		"Remove":        reflect.ValueOf(pipes.Remove),
		"RemoveFlat":    reflect.ValueOf(pipes.RemoveFlat),
		"Sync":          reflect.ValueOf(pipes.Sync),
	}
}
