// Code generated by 'yaegi extract github.com/gookit/goutil/dump'. DO NOT EDIT.

package symbols

import (
	"github.com/gookit/goutil/dump"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/gookit/goutil/dump/dump"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BytesAsString":     reflect.ValueOf(dump.BytesAsString),
		"Clear":             reflect.ValueOf(dump.Clear),
		"Config":            reflect.ValueOf(dump.Config),
		"Ffile":             reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"Ffname":            reflect.ValueOf(constant.MakeFromLiteral("8", token.INT, 0)),
		"Ffunc":             reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"Fline":             reflect.ValueOf(constant.MakeFromLiteral("16", token.INT, 0)),
		"Fnopos":            reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"Format":            reflect.ValueOf(dump.Format),
		"Fprint":            reflect.ValueOf(dump.Fprint),
		"NewDefaultOptions": reflect.ValueOf(dump.NewDefaultOptions),
		"NewDumper":         reflect.ValueOf(dump.NewDumper),
		"NewWithOptions":    reflect.ValueOf(dump.NewWithOptions),
		"NoLoc":             reflect.ValueOf(dump.NoLoc),
		"P":                 reflect.ValueOf(dump.P),
		"Print":             reflect.ValueOf(dump.Print),
		"Println":           reflect.ValueOf(dump.Println),
		"Reset":             reflect.ValueOf(dump.Reset),
		"Reset2":            reflect.ValueOf(dump.Reset2),
		"SkipNilField":      reflect.ValueOf(dump.SkipNilField),
		"SkipPrivate":       reflect.ValueOf(dump.SkipPrivate),
		"Std":               reflect.ValueOf(dump.Std),
		"Std2":              reflect.ValueOf(dump.Std2),
		"V":                 reflect.ValueOf(dump.V),
		"WithCallerSkip":    reflect.ValueOf(dump.WithCallerSkip),
		"WithoutColor":      reflect.ValueOf(dump.WithoutColor),
		"WithoutLen":        reflect.ValueOf(dump.WithoutLen),
		"WithoutOutput":     reflect.ValueOf(dump.WithoutOutput),
		"WithoutPosition":   reflect.ValueOf(dump.WithoutPosition),
		"WithoutType":       reflect.ValueOf(dump.WithoutType),

		// type definitions
		"Dumper":     reflect.ValueOf((*dump.Dumper)(nil)),
		"OptionFunc": reflect.ValueOf((*dump.OptionFunc)(nil)),
		"Options":    reflect.ValueOf((*dump.Options)(nil)),
		"Theme":      reflect.ValueOf((*dump.Theme)(nil)),
	}
}
