// Code generated by 'yaegi extract github.com/pancsta/asyncmachine-go/pkg/states'. DO NOT EDIT.

package symbols

import (
	"github.com/pancsta/asyncmachine-go/pkg/states"
	"reflect"
)

func init() {
	Symbols["github.com/pancsta/asyncmachine-go/pkg/states/states"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddErrConnecting":   reflect.ValueOf(states.AddErrConnecting),
		"BasicSchema":        reflect.ValueOf(&states.BasicSchema).Elem(),
		"BasicStates":        reflect.ValueOf(&states.BasicStates).Elem(),
		"ConnPoolGroups":     reflect.ValueOf(&states.ConnPoolGroups).Elem(),
		"ConnPoolSchema":     reflect.ValueOf(&states.ConnPoolSchema).Elem(),
		"ConnPoolStates":     reflect.ValueOf(&states.ConnPoolStates).Elem(),
		"ConnectedGroups":    reflect.ValueOf(&states.ConnectedGroups).Elem(),
		"ConnectedSchema":    reflect.ValueOf(&states.ConnectedSchema).Elem(),
		"ConnectedStates":    reflect.ValueOf(&states.ConnectedStates).Elem(),
		"DisposedArgHandler": reflect.ValueOf(&states.DisposedArgHandler).Elem(),
		"DisposedGroups":     reflect.ValueOf(&states.DisposedGroups).Elem(),
		"DisposedSchema":     reflect.ValueOf(&states.DisposedSchema).Elem(),
		"DisposedStates":     reflect.ValueOf(&states.DisposedStates).Elem(),
		"ErrConnecting":      reflect.ValueOf(&states.ErrConnecting).Elem(),
		"StatesUtilsFile":    reflect.ValueOf(&states.StatesUtilsFile).Elem(),

		// type definitions
		"BasicStatesDef":     reflect.ValueOf((*states.BasicStatesDef)(nil)),
		"ConnPoolGroupsDef":  reflect.ValueOf((*states.ConnPoolGroupsDef)(nil)),
		"ConnPoolState":      reflect.ValueOf((*states.ConnPoolState)(nil)),
		"ConnPoolStatesDef":  reflect.ValueOf((*states.ConnPoolStatesDef)(nil)),
		"ConnectedGroupsDef": reflect.ValueOf((*states.ConnectedGroupsDef)(nil)),
		"ConnectedStatesDef": reflect.ValueOf((*states.ConnectedStatesDef)(nil)),
		"DisposedGroupsDef":  reflect.ValueOf((*states.DisposedGroupsDef)(nil)),
		"DisposedHandlers":   reflect.ValueOf((*states.DisposedHandlers)(nil)),
		"DisposedStatesDef":  reflect.ValueOf((*states.DisposedStatesDef)(nil)),
	}
}
