// Code generated by 'yaegi extract github.com/pancsta/asyncmachine-go/pkg/rpc'. DO NOT EDIT.

package symbols

import (
	"context"
	"github.com/pancsta/asyncmachine-go/pkg/rpc"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/pancsta/asyncmachine-go/pkg/rpc/rpc"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"APrefix":                  reflect.ValueOf(constant.MakeFromLiteral("\"am_rpc\"", token.STRING, 0)),
		"AddErr":                   reflect.ValueOf(rpc.AddErr),
		"AddErrNetwork":            reflect.ValueOf(rpc.AddErrNetwork),
		"AddErrNetworkTimeout":     reflect.ValueOf(rpc.AddErrNetworkTimeout),
		"AddErrNoConn":             reflect.ValueOf(rpc.AddErrNoConn),
		"AddErrParams":             reflect.ValueOf(rpc.AddErrParams),
		"AddErrResp":               reflect.ValueOf(rpc.AddErrResp),
		"AddErrRpcStr":             reflect.ValueOf(rpc.AddErrRpcStr),
		"ArgsRpc":                  reflect.ValueOf(&rpc.ArgsRpc).Elem(),
		"BindMux":                  reflect.ValueOf(rpc.BindMux),
		"BindServer":               reflect.ValueOf(rpc.BindServer),
		"BindServerMulti":          reflect.ValueOf(rpc.BindServerMulti),
		"BindServerRpcReady":       reflect.ValueOf(rpc.BindServerRpcReady),
		"Checksum":                 reflect.ValueOf(rpc.Checksum),
		"ClientBye":                reflect.ValueOf(&rpc.ClientBye).Elem(),
		"ClientMethods":            reflect.ValueOf(&rpc.ClientMethods).Elem(),
		"ClientPushAllTicks":       reflect.ValueOf(&rpc.ClientPushAllTicks).Elem(),
		"ClientSchemaChange":       reflect.ValueOf(&rpc.ClientSchemaChange).Elem(),
		"ClientSendPayload":        reflect.ValueOf(&rpc.ClientSendPayload).Elem(),
		"ClientUpdate":             reflect.ValueOf(&rpc.ClientUpdate).Elem(),
		"ClientUpdateMutations":    reflect.ValueOf(&rpc.ClientUpdateMutations).Elem(),
		"EnableDebuggingRpc":       reflect.ValueOf(rpc.EnableDebuggingRpc),
		"EnvAmReplAddr":            reflect.ValueOf(constant.MakeFromLiteral("\"AM_REPL_ADDR\"", token.STRING, 0)),
		"EnvAmReplDir":             reflect.ValueOf(constant.MakeFromLiteral("\"AM_REPL_DIR\"", token.STRING, 0)),
		"EnvAmRpcDbg":              reflect.ValueOf(constant.MakeFromLiteral("\"AM_RPC_DBG\"", token.STRING, 0)),
		"EnvAmRpcLogClient":        reflect.ValueOf(constant.MakeFromLiteral("\"AM_RPC_LOG_CLIENT\"", token.STRING, 0)),
		"EnvAmRpcLogClientVerbose": reflect.ValueOf(constant.MakeFromLiteral("\"AM_RPC_LOG_CLIENT_VERBOSE\"", token.STRING, 0)),
		"EnvAmRpcLogMux":           reflect.ValueOf(constant.MakeFromLiteral("\"AM_RPC_LOG_MUX\"", token.STRING, 0)),
		"EnvAmRpcLogServer":        reflect.ValueOf(constant.MakeFromLiteral("\"AM_RPC_LOG_SERVER\"", token.STRING, 0)),
		"ErrDestination":           reflect.ValueOf(&rpc.ErrDestination).Elem(),
		"ErrInvalidParams":         reflect.ValueOf(&rpc.ErrInvalidParams).Elem(),
		"ErrInvalidResp":           reflect.ValueOf(&rpc.ErrInvalidResp).Elem(),
		"ErrNetwork":               reflect.ValueOf(&rpc.ErrNetwork).Elem(),
		"ErrNetworkTimeout":        reflect.ValueOf(&rpc.ErrNetworkTimeout).Elem(),
		"ErrNoAccess":              reflect.ValueOf(&rpc.ErrNoAccess).Elem(),
		"ErrNoConn":                reflect.ValueOf(&rpc.ErrNoConn).Elem(),
		"ErrRpc":                   reflect.ValueOf(&rpc.ErrRpc).Elem(),
		"GetClientId":              reflect.ValueOf(rpc.GetClientId),
		"KindClient":               reflect.ValueOf(rpc.KindClient),
		"KindServer":               reflect.ValueOf(rpc.KindServer),
		"MachRepl":                 reflect.ValueOf(rpc.MachRepl),
		"MachReplEnv":              reflect.ValueOf(rpc.MachReplEnv),
		"MachReplWs":               reflect.ValueOf(rpc.MachReplWs),
		"NewClient":                reflect.ValueOf(rpc.NewClient),
		"NewMsgpackCodec":          reflect.ValueOf(rpc.NewMsgpackCodec),
		"NewMux":                   reflect.ValueOf(rpc.NewMux),
		"NewNetworkMachine":        reflect.ValueOf(rpc.NewNetworkMachine),
		"NewServer":                reflect.ValueOf(rpc.NewServer),
		"Pass":                     reflect.ValueOf(&rpc.Pass).Elem(),
		"PrefixNetMach":            reflect.ValueOf(constant.MakeFromLiteral("\"rnm-\"", token.STRING, 0)),
		"ServerAdd":                reflect.ValueOf(&rpc.ServerAdd).Elem(),
		"ServerAddNS":              reflect.ValueOf(&rpc.ServerAddNS).Elem(),
		"ServerArgs":               reflect.ValueOf(&rpc.ServerArgs).Elem(),
		"ServerBye":                reflect.ValueOf(&rpc.ServerBye).Elem(),
		"ServerHandshake":          reflect.ValueOf(&rpc.ServerHandshake).Elem(),
		"ServerHello":              reflect.ValueOf(&rpc.ServerHello).Elem(),
		"ServerLog":                reflect.ValueOf(&rpc.ServerLog).Elem(),
		"ServerMethods":            reflect.ValueOf(&rpc.ServerMethods).Elem(),
		"ServerRemove":             reflect.ValueOf(&rpc.ServerRemove).Elem(),
		"ServerSet":                reflect.ValueOf(&rpc.ServerSet).Elem(),
		"ServerSync":               reflect.ValueOf(&rpc.ServerSync).Elem(),
		"TagRpcClient":             reflect.ValueOf(constant.MakeFromLiteral("\"rpc-client\"", token.STRING, 0)),
		"TagRpcHandler":            reflect.ValueOf(constant.MakeFromLiteral("\"rpc-handler\"", token.STRING, 0)),
		"TagRpcMux":                reflect.ValueOf(constant.MakeFromLiteral("\"rpc-mux\"", token.STRING, 0)),
		"TagRpcServer":             reflect.ValueOf(constant.MakeFromLiteral("\"rpc-server\"", token.STRING, 0)),
		"WsDialPath":               reflect.ValueOf(rpc.WsDialPath),
		"WsListenPath":             reflect.ValueOf(rpc.WsListenPath),
		"WsPathDial":               reflect.ValueOf(constant.MakeFromLiteral("\"/dial/\"", token.STRING, 0)),
		"WsPathListen":             reflect.ValueOf(constant.MakeFromLiteral("\"/listen/\"", token.STRING, 0)),

		// type definitions
		"A":                reflect.ValueOf((*rpc.A)(nil)),
		"AClientConnected": reflect.ValueOf((*rpc.AClientConnected)(nil)),
		"AServerPayload":   reflect.ValueOf((*rpc.AServerPayload)(nil)),
		"Args":             reflect.ValueOf((*rpc.Args)(nil)),
		"Client":           reflect.ValueOf((*rpc.Client)(nil)),
		"ClientMethod":     reflect.ValueOf((*rpc.ClientMethod)(nil)),
		"ClientOpts":       reflect.ValueOf((*rpc.ClientOpts)(nil)),
		"ClockUpdateFunc":  reflect.ValueOf((*rpc.ClockUpdateFunc)(nil)),
		"ExceptionHandler": reflect.ValueOf((*rpc.ExceptionHandler)(nil)),
		"Kind":             reflect.ValueOf((*rpc.Kind)(nil)),
		"MsgCliHello":      reflect.ValueOf((*rpc.MsgCliHello)(nil)),
		"MsgCliMutation":   reflect.ValueOf((*rpc.MsgCliMutation)(nil)),
		"MsgEmpty":         reflect.ValueOf((*rpc.MsgEmpty)(nil)),
		"MsgSrvArgs":       reflect.ValueOf((*rpc.MsgSrvArgs)(nil)),
		"MsgSrvHello":      reflect.ValueOf((*rpc.MsgSrvHello)(nil)),
		"MsgSrvMutation":   reflect.ValueOf((*rpc.MsgSrvMutation)(nil)),
		"MsgSrvPayload":    reflect.ValueOf((*rpc.MsgSrvPayload)(nil)),
		"MsgSrvSync":       reflect.ValueOf((*rpc.MsgSrvSync)(nil)),
		"MsgSrvUpdate":     reflect.ValueOf((*rpc.MsgSrvUpdate)(nil)),
		"MsgSrvUpdateMuts": reflect.ValueOf((*rpc.MsgSrvUpdateMuts)(nil)),
		"Mux":              reflect.ValueOf((*rpc.Mux)(nil)),
		"MuxNewServerFn":   reflect.ValueOf((*rpc.MuxNewServerFn)(nil)),
		"MuxOpts":          reflect.ValueOf((*rpc.MuxOpts)(nil)),
		"NetMachConn":      reflect.ValueOf((*rpc.NetMachConn)(nil)),
		"NetMachInternal":  reflect.ValueOf((*rpc.NetMachInternal)(nil)),
		"NetworkMachine":   reflect.ValueOf((*rpc.NetworkMachine)(nil)),
		"ReplOpts":         reflect.ValueOf((*rpc.ReplOpts)(nil)),
		"Server":           reflect.ValueOf((*rpc.Server)(nil)),
		"ServerMethod":     reflect.ValueOf((*rpc.ServerMethod)(nil)),
		"ServerOpts":       reflect.ValueOf((*rpc.ServerOpts)(nil)),

		// interface wrapper definitions
		"_NetMachConn": reflect.ValueOf((*_github_com_pancsta_asyncmachine_go_pkg_rpc_NetMachConn)(nil)),
	}
}

// _github_com_pancsta_asyncmachine_go_pkg_rpc_NetMachConn is an interface wrapper for NetMachConn type
type _github_com_pancsta_asyncmachine_go_pkg_rpc_NetMachConn struct {
	IValue  interface{}
	WCall   func(ctx context.Context, method rpc.ServerMethod, args any, resp any) bool
	WNotify func(ctx context.Context, method rpc.ServerMethod, args any) bool
}

func (W _github_com_pancsta_asyncmachine_go_pkg_rpc_NetMachConn) Call(ctx context.Context, method rpc.ServerMethod, args any, resp any) bool {
	return W.WCall(ctx, method, args, resp)
}
func (W _github_com_pancsta_asyncmachine_go_pkg_rpc_NetMachConn) Notify(ctx context.Context, method rpc.ServerMethod, args any) bool {
	return W.WNotify(ctx, method, args)
}
