// Code generated by 'yaegi extract github.com/pancsta/asyncmachine-go/pkg/rpc/states'. DO NOT EDIT.

package symbols

import (
	"github.com/pancsta/asyncmachine-go/pkg/machine"
	"github.com/pancsta/asyncmachine-go/pkg/rpc/states"
	"reflect"
)

func init() {
	Symbols["github.com/pancsta/asyncmachine-go/pkg/rpc/states/states"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ClientGroups":      reflect.ValueOf(&states.ClientGroups).Elem(),
		"ClientSchema":      reflect.ValueOf(&states.ClientSchema).Elem(),
		"ClientStates":      reflect.ValueOf(&states.ClientStates).Elem(),
		"ConsumerSchema":    reflect.ValueOf(&states.ConsumerSchema).Elem(),
		"ConsumerStates":    reflect.ValueOf(&states.ConsumerStates).Elem(),
		"MuxGroups":         reflect.ValueOf(&states.MuxGroups).Elem(),
		"MuxSchema":         reflect.ValueOf(&states.MuxSchema).Elem(),
		"MuxStates":         reflect.ValueOf(&states.MuxStates).Elem(),
		"ServerGroups":      reflect.ValueOf(&states.ServerGroups).Elem(),
		"ServerSchema":      reflect.ValueOf(&states.ServerSchema).Elem(),
		"ServerStates":      reflect.ValueOf(&states.ServerStates).Elem(),
		"SharedGroups":      reflect.ValueOf(&states.SharedGroups).Elem(),
		"SharedSchema":      reflect.ValueOf(&states.SharedSchema).Elem(),
		"SharedStates":      reflect.ValueOf(&states.SharedStates).Elem(),
		"StateSourceSchema": reflect.ValueOf(&states.StateSourceSchema).Elem(),
		"StateSourceStates": reflect.ValueOf(&states.StateSourceStates).Elem(),

		// type definitions
		"ClientGroupsDef":      reflect.ValueOf((*states.ClientGroupsDef)(nil)),
		"ClientStatesDef":      reflect.ValueOf((*states.ClientStatesDef)(nil)),
		"ConsumerHandlers":     reflect.ValueOf((*states.ConsumerHandlers)(nil)),
		"ConsumerStatesDef":    reflect.ValueOf((*states.ConsumerStatesDef)(nil)),
		"MuxGroupsDef":         reflect.ValueOf((*states.MuxGroupsDef)(nil)),
		"MuxStatesDef":         reflect.ValueOf((*states.MuxStatesDef)(nil)),
		"ServerGroupsDef":      reflect.ValueOf((*states.ServerGroupsDef)(nil)),
		"ServerStatesDef":      reflect.ValueOf((*states.ServerStatesDef)(nil)),
		"SharedGroupsDef":      reflect.ValueOf((*states.SharedGroupsDef)(nil)),
		"SharedStatesDef":      reflect.ValueOf((*states.SharedStatesDef)(nil)),
		"StateSourceStatesDef": reflect.ValueOf((*states.StateSourceStatesDef)(nil)),

		// interface wrapper definitions
		"_ConsumerHandlers": reflect.ValueOf((*_github_com_pancsta_asyncmachine_go_pkg_rpc_states_ConsumerHandlers)(nil)),
	}
}

// _github_com_pancsta_asyncmachine_go_pkg_rpc_states_ConsumerHandlers is an interface wrapper for ConsumerHandlers type
type _github_com_pancsta_asyncmachine_go_pkg_rpc_states_ConsumerHandlers struct {
	IValue              interface{}
	WServerPayloadState func(e *machine.Event)
}

func (W _github_com_pancsta_asyncmachine_go_pkg_rpc_states_ConsumerHandlers) ServerPayloadState(e *machine.Event) {
	W.WServerPayloadState(e)
}
