// Code generated by am-gen; DO NOT EDIT.
//go:build tinygo

package mux

import am "github.com/pancsta/asyncmachine-go/pkg/machine"

func MuxNegotiations(h *Mux) map[string]am.HandlerNegotiation {
	return map[string]am.HandlerNegotiation{
		"NewServerErrEnter": h.NewServerErrEnter,
		"StartEnter":        h.StartEnter,
	}
}

func MuxFinals(h *Mux) map[string]am.HandlerFinal {
	return map[string]am.HandlerFinal{
		"ClientConnectedState": h.ClientConnectedState,
		"ExceptionState":       h.ExceptionState,
		"HasClientsEnd":        h.HasClientsEnd,
		"HealthcheckState":     h.HealthcheckState,
		"NewServerErrState":    h.NewServerErrState,
		"StartEnd":             h.StartEnd,
		"StartState":           h.StartState,
	}
}
