// Code generated by am-gen; DO NOT EDIT.
//go:build tinygo

package tinygo

import am "github.com/pancsta/asyncmachine-go/pkg/machine"

func MachineHandlersNegotiations(h *MachineHandlers) map[string]am.HandlerNegotiation {
	return map[string]am.HandlerNegotiation{}
}

func MachineHandlersFinals(h *MachineHandlers) map[string]am.HandlerFinal {
	return map[string]am.HandlerFinal{
		"DownloadingFileState": h.DownloadingFileState,
		"ExceptionState":       h.ExceptionState,
		"ProcessingFileEnd":    h.ProcessingFileEnd,
		"ProcessingFileState":  h.ProcessingFileState,
		"UploadingFileEnd":     h.UploadingFileEnd,
		"UploadingFileState":   h.UploadingFileState,
	}
}
