// Code generated by am-gen; DO NOT EDIT.
//go:build tinygo

package states

import am "github.com/pancsta/asyncmachine-go/pkg/machine"

// S is a type alias for a list of state names.
type S = am.S

// ///// ///// /////

// ///// BOOTSTRAP

// ///// ///// /////

// BootstrapStatesDef contains states for Bootstrap.
type BootstrapStatesDef struct {
	*am.StatesBase
	WorkerAddr        string
	ErrNetwork        string
	ErrHandlerTimeout string
	Start             string
	Ready             string
	Healthcheck       string
	Heartbeat         string
	ErrOnClient       string
	ErrProviding      string
	ErrSendPayload    string
	SendPayload       string
}

// BootstrapGroupsDef contains all the state groups of the Bootstrap state schema.
type BootstrapGroupsDef struct{}

// BootstrapSchema represents all relations and properties of BootstrapStates.
var BootstrapSchema = am.Schema{
	ssB.ErrHandlerTimeout: {
		Add:     S{ssB.Exception},
		Multi:   true,
		Require: S{ssB.Exception},
	},
	ssB.ErrNetwork: {
		Add:     S{ssB.Exception},
		Multi:   true,
		Require: S{ssB.Exception},
	},
	ssB.ErrOnClient:    {Require: S{ssB.Exception}},
	ssB.ErrProviding:   {Require: S{ssB.Exception}},
	ssB.ErrSendPayload: {Require: S{ssB.Exception}},
	ssB.Exception:      {Multi: true},
	ssB.Healthcheck:    {Multi: true},
	ssB.Heartbeat:      {},
	ssB.Ready:          {Require: S{ssB.Start}},
	ssB.SendPayload:    {Multi: true},
	ssB.Start:          {},
	ssB.WorkerAddr:     {},
}

// EXPORTS AND GROUPS
var (
	ssB = BootstrapStatesDef{
		ErrHandlerTimeout: "ErrHandlerTimeout",
		ErrNetwork:        "ErrNetwork",
		ErrOnClient:       "ErrOnClient",
		ErrProviding:      "ErrProviding",
		ErrSendPayload:    "ErrSendPayload",
		Healthcheck:       "Healthcheck",
		Heartbeat:         "Heartbeat",
		Ready:             "Ready",
		SendPayload:       "SendPayload",
		Start:             "Start",
		StatesBase:        &am.StatesBase{Exception: "Exception"},
		WorkerAddr:        "WorkerAddr",
	}
	sgB = BootstrapGroupsDef{}

	// BootstrapStates contains all the states for the Bootstrap state schema.
	BootstrapStates = ssB

	// BootstrapGroups contains all the state groups for the Bootstrap state schema.
	BootstrapGroups = sgB
)

func init() {
	ssB.SetNames(S{"Exception", "WorkerAddr", "ErrNetwork", "ErrHandlerTimeout", "Start", "Ready", "Healthcheck", "Heartbeat", "ErrOnClient", "ErrProviding", "ErrSendPayload", "SendPayload"})
	groups := map[string][]int{}
	ssB.SetStateGroups(groups, []string{})
}

// ///// ///// /////

// ///// SUPERVISOR

// ///// ///// /////

// SupervisorStatesDef contains states for Supervisor.
type SupervisorStatesDef struct {
	*am.StatesBase
	ErrWorker          string
	ErrPool            string
	LocalRpcReady      string
	PublicRpcReady     string
	Ready              string
	Heartbeat          string
	PoolStarting       string
	NormalizingPool    string
	PoolNormalized     string
	PoolReady          string
	WorkersAvailable   string
	ListWorkers        string
	SetWorker          string
	ForkWorker         string
	ForkingWorker      string
	WorkerConnected    string
	WorkerForked       string
	KillWorker         string
	KillingWorker      string
	WorkerKilled       string
	WorkerReady        string
	WorkerGone         string
	ClientConnected    string
	ClientDisconnected string
	ProvideWorker      string
	WorkerIssues       string
	ClientSendPayload  string
	SuperConnected     string
	SuperDisconnected  string
	SuperSendPayload   string
	ErrNetwork         string
	ErrHandlerTimeout  string
	Start              string
	Healthcheck        string
	ErrOnClient        string
	ErrProviding       string
	ErrSendPayload     string
	SendPayload        string
}

// SupervisorGroupsDef contains all the state groups of the Supervisor state schema.
type SupervisorGroupsDef struct{}

// SupervisorSchema represents all relations and properties of SupervisorStates.
var SupervisorSchema = am.Schema{
	ssS.ClientConnected:    {Multi: true},
	ssS.ClientDisconnected: {Multi: true},
	ssS.ClientSendPayload:  {Multi: true},
	ssS.ErrHandlerTimeout: {
		Add:     S{ssS.Exception},
		Multi:   true,
		Require: S{ssS.Exception},
	},
	ssS.ErrNetwork: {
		Add:     S{ssS.Exception},
		Multi:   true,
		Require: S{ssS.Exception},
	},
	ssS.ErrOnClient: {Require: S{ssS.Exception}},
	ssS.ErrPool: {
		Add:     S{ssS.NormalizingPool},
		Remove:  S{ssS.PoolNormalized},
		Require: S{ssS.Exception},
	},
	ssS.ErrProviding:   {Require: S{ssS.Exception}},
	ssS.ErrSendPayload: {Require: S{ssS.Exception}},
	ssS.ErrWorker: {
		Add:     S{ssS.NormalizingPool, ssS.Heartbeat},
		Require: S{ssS.Exception},
	},
	ssS.Exception: {Multi: true},
	ssS.ForkWorker: {
		Multi:   true,
		Require: S{ssS.Start},
	},
	ssS.ForkingWorker: {
		Multi:   true,
		Require: S{ssS.Start},
	},
	ssS.Healthcheck:   {Multi: true},
	ssS.Heartbeat:     {Require: S{ssS.Start}},
	ssS.KillWorker:    {Multi: true},
	ssS.KillingWorker: {Multi: true},
	ssS.ListWorkers: {
		Multi:   true,
		Require: S{ssS.Start},
	},
	ssS.LocalRpcReady: {Require: S{ssS.Start}},
	ssS.NormalizingPool: {
		After:   S{ssS.ErrWorker},
		Remove:  S{ssS.PoolNormalized, ssS.NormalizingPool},
		Require: S{ssS.Start},
	},
	ssS.PoolNormalized: {
		Add:     S{ssS.Heartbeat},
		Remove:  S{ssS.PoolNormalized, ssS.NormalizingPool},
		Require: S{ssS.Start},
	},
	ssS.PoolReady: {
		Add:     S{ssS.Heartbeat},
		Remove:  S{ssS.PoolStarting, ssS.PoolReady},
		Require: S{ssS.Start},
	},
	ssS.PoolStarting: {
		Add:    S{ssS.NormalizingPool},
		Remove: S{ssS.PoolStarting, ssS.PoolReady},
	},
	ssS.ProvideWorker: {
		Multi:   true,
		Require: S{ssS.WorkersAvailable},
	},
	ssS.PublicRpcReady: {Require: S{ssS.Start}},
	ssS.Ready:          {Require: S{ssS.LocalRpcReady, ssS.PublicRpcReady, ssS.PoolReady}},
	ssS.SendPayload:    {Add: S{ssS.ErrSendPayload, ssS.Exception}},
	ssS.SetWorker: {
		Multi:   true,
		Require: S{ssS.Start},
	},
	ssS.Start:             {Add: S{ssS.PoolStarting}},
	ssS.SuperConnected:    {Multi: true},
	ssS.SuperDisconnected: {Multi: true},
	ssS.SuperSendPayload:  {Multi: true},
	ssS.WorkerConnected: {
		Multi:   true,
		Require: S{ssS.Start},
	},
	ssS.WorkerForked: {
		Add:     S{ssS.Heartbeat},
		Multi:   true,
		Require: S{ssS.Start},
	},
	ssS.WorkerGone: {
		Multi:   true,
		Remove:  S{ssS.PoolReady},
		Require: S{ssS.Start},
	},
	ssS.WorkerIssues: {Multi: true},
	ssS.WorkerKilled: {
		Add:   S{ssS.NormalizingPool, ssS.Heartbeat},
		Multi: true,
	},
	ssS.WorkerReady: {
		Add:     S{ssS.PoolReady},
		Multi:   true,
		Require: S{ssS.Start},
	},
	ssS.WorkersAvailable: {Require: S{ssS.PoolReady}},
}

// EXPORTS AND GROUPS
var (
	ssS = SupervisorStatesDef{
		ClientConnected:    "ClientConnected",
		ClientDisconnected: "ClientDisconnected",
		ClientSendPayload:  "ClientSendPayload",
		ErrHandlerTimeout:  "ErrHandlerTimeout",
		ErrNetwork:         "ErrNetwork",
		ErrOnClient:        "ErrOnClient",
		ErrPool:            "ErrPool",
		ErrProviding:       "ErrProviding",
		ErrSendPayload:     "ErrSendPayload",
		ErrWorker:          "ErrWorker",
		ForkWorker:         "ForkWorker",
		ForkingWorker:      "ForkingWorker",
		Healthcheck:        "Healthcheck",
		Heartbeat:          "Heartbeat",
		KillWorker:         "KillWorker",
		KillingWorker:      "KillingWorker",
		ListWorkers:        "ListWorkers",
		LocalRpcReady:      "LocalRpcReady",
		NormalizingPool:    "NormalizingPool",
		PoolNormalized:     "PoolNormalized",
		PoolReady:          "PoolReady",
		PoolStarting:       "PoolStarting",
		ProvideWorker:      "ProvideWorker",
		PublicRpcReady:     "PublicRpcReady",
		Ready:              "Ready",
		SendPayload:        "SendPayload",
		SetWorker:          "SetWorker",
		Start:              "Start",
		StatesBase:         &am.StatesBase{Exception: "Exception"},
		SuperConnected:     "SuperConnected",
		SuperDisconnected:  "SuperDisconnected",
		SuperSendPayload:   "SuperSendPayload",
		WorkerConnected:    "WorkerConnected",
		WorkerForked:       "WorkerForked",
		WorkerGone:         "WorkerGone",
		WorkerIssues:       "WorkerIssues",
		WorkerKilled:       "WorkerKilled",
		WorkerReady:        "WorkerReady",
		WorkersAvailable:   "WorkersAvailable",
	}
	sgS = SupervisorGroupsDef{}

	// SupervisorStates contains all the states for the Supervisor state schema.
	SupervisorStates = ssS

	// SupervisorGroups contains all the state groups for the Supervisor state schema.
	SupervisorGroups = sgS
)

func init() {
	ssS.SetNames(S{"Exception", "ErrWorker", "ErrPool", "LocalRpcReady", "PublicRpcReady", "Ready", "Heartbeat", "PoolStarting", "NormalizingPool", "PoolNormalized", "PoolReady", "WorkersAvailable", "ListWorkers", "SetWorker", "ForkWorker", "ForkingWorker", "WorkerConnected", "WorkerForked", "KillWorker", "KillingWorker", "WorkerKilled", "WorkerReady", "WorkerGone", "ClientConnected", "ClientDisconnected", "ProvideWorker", "WorkerIssues", "ClientSendPayload", "SuperConnected", "SuperDisconnected", "SuperSendPayload", "ErrNetwork", "ErrHandlerTimeout", "Start", "Healthcheck", "ErrOnClient", "ErrProviding", "ErrSendPayload", "SendPayload"})
	groups := map[string][]int{}
	ssS.SetStateGroups(groups, []string{})
}

// ///// ///// /////

// ///// WORKER

// ///// ///// /////

// WorkerStatesDef contains states for Worker.
type WorkerStatesDef struct {
	*am.StatesBase
	ErrWork           string
	ErrWorkTimeout    string
	ErrClient         string
	ErrSupervisor     string
	Ready             string
	LocalRpcReady     string
	PublicRpcReady    string
	RpcReady          string
	SuperConnected    string
	ServeClient       string
	ClientConnected   string
	ClientSendPayload string
	SuperSendPayload  string
	Idle              string
	WorkRequested     string
	Working           string
	WorkReady         string
	ErrNetwork        string
	ErrHandlerTimeout string
	Start             string
	Healthcheck       string
	Heartbeat         string
	ErrOnClient       string
	ErrProviding      string
	ErrSendPayload    string
	SendPayload       string
}

// WorkerGroupsDef contains all the state groups of the Worker state schema.
type WorkerGroupsDef struct {
	WorkStatus S
}

// WorkerSchema represents all relations and properties of WorkerStates.
var WorkerSchema = am.Schema{
	ssW.ClientConnected:   {Require: S{ssW.Start}},
	ssW.ClientSendPayload: {Require: S{ssW.PublicRpcReady}},
	ssW.ErrClient:         {Require: S{ssW.Exception}},
	ssW.ErrHandlerTimeout: {
		Add:     S{ssW.Exception},
		Multi:   true,
		Require: S{ssW.Exception},
	},
	ssW.ErrNetwork: {
		Add:     S{ssW.Exception},
		Multi:   true,
		Require: S{ssW.Exception},
	},
	ssW.ErrOnClient:    {Require: S{ssW.Exception}},
	ssW.ErrProviding:   {Require: S{ssW.Exception}},
	ssW.ErrSendPayload: {Require: S{ssW.Exception}},
	ssW.ErrSupervisor:  {Require: S{ssW.Exception}},
	ssW.ErrWork:        {Require: S{ssW.Exception}},
	ssW.ErrWorkTimeout: {Require: S{ssW.Exception}},
	ssW.Exception:      {Multi: true},
	ssW.Healthcheck:    {Multi: true},
	ssW.Heartbeat:      {},
	ssW.Idle: {
		Auto:    true,
		Remove:  S{ssW.WorkRequested, ssW.Working, ssW.WorkReady, ssW.Idle},
		Require: S{ssW.Ready},
	},
	ssW.LocalRpcReady:  {Require: S{ssW.Start}},
	ssW.PublicRpcReady: {Require: S{ssW.Start}},
	ssW.Ready:          {Require: S{ssW.LocalRpcReady}},
	ssW.RpcReady: {
		Auto:    true,
		Require: S{ssW.LocalRpcReady, ssW.PublicRpcReady},
	},
	ssW.SendPayload:      {Add: S{ssW.ErrSendPayload, ssW.Exception}},
	ssW.ServeClient:      {Require: S{ssW.PublicRpcReady}},
	ssW.Start:            {},
	ssW.SuperConnected:   {Require: S{ssW.Start}},
	ssW.SuperSendPayload: {Require: S{ssW.LocalRpcReady}},
	ssW.WorkReady: {
		Remove:  S{ssW.WorkRequested, ssW.Working, ssW.WorkReady, ssW.Idle},
		Require: S{ssW.Ready},
	},
	ssW.WorkRequested: {
		Remove:  S{ssW.WorkRequested, ssW.Working, ssW.WorkReady, ssW.Idle},
		Require: S{ssW.Ready},
	},
	ssW.Working: {
		Remove:  S{ssW.WorkRequested, ssW.Working, ssW.WorkReady, ssW.Idle},
		Require: S{ssW.Ready},
	},
}

// EXPORTS AND GROUPS
var (
	ssW = WorkerStatesDef{
		ClientConnected:   "ClientConnected",
		ClientSendPayload: "ClientSendPayload",
		ErrClient:         "ErrClient",
		ErrHandlerTimeout: "ErrHandlerTimeout",
		ErrNetwork:        "ErrNetwork",
		ErrOnClient:       "ErrOnClient",
		ErrProviding:      "ErrProviding",
		ErrSendPayload:    "ErrSendPayload",
		ErrSupervisor:     "ErrSupervisor",
		ErrWork:           "ErrWork",
		ErrWorkTimeout:    "ErrWorkTimeout",
		Healthcheck:       "Healthcheck",
		Heartbeat:         "Heartbeat",
		Idle:              "Idle",
		LocalRpcReady:     "LocalRpcReady",
		PublicRpcReady:    "PublicRpcReady",
		Ready:             "Ready",
		RpcReady:          "RpcReady",
		SendPayload:       "SendPayload",
		ServeClient:       "ServeClient",
		Start:             "Start",
		StatesBase:        &am.StatesBase{Exception: "Exception"},
		SuperConnected:    "SuperConnected",
		SuperSendPayload:  "SuperSendPayload",
		WorkReady:         "WorkReady",
		WorkRequested:     "WorkRequested",
		Working:           "Working",
	}
	sgW = WorkerGroupsDef{WorkStatus: S{ssW.WorkRequested, ssW.Working, ssW.WorkReady, ssW.Idle}}

	// WorkerStates contains all the states for the Worker state schema.
	WorkerStates = ssW

	// WorkerGroups contains all the state groups for the Worker state schema.
	WorkerGroups = sgW
)

func init() {
	ssW.SetNames(S{"Exception", "ErrWork", "ErrWorkTimeout", "ErrClient", "ErrSupervisor", "Ready", "LocalRpcReady", "PublicRpcReady", "RpcReady", "SuperConnected", "ServeClient", "ClientConnected", "ClientSendPayload", "SuperSendPayload", "Idle", "WorkRequested", "Working", "WorkReady", "ErrNetwork", "ErrHandlerTimeout", "Start", "Healthcheck", "Heartbeat", "ErrOnClient", "ErrProviding", "ErrSendPayload", "SendPayload"})
	groups := map[string][]int{"WorkStatus": {15, 16, 17, 14}}
	ssW.SetStateGroups(groups, []string{"WorkStatus"})
}

// ///// ///// /////

// ///// CLIENT

// ///// ///// /////

// ClientStatesDef contains states for Client.
type ClientStatesDef struct {
	*am.StatesBase
	ErrWorker           string
	ErrSupervisor       string
	WorkerDisconnected  string
	WorkerConnecting    string
	WorkerConnected     string
	WorkerDisconnecting string
	WorkerReady         string
	Ready               string
	SuperDisconnected   string
	SuperConnecting     string
	SuperConnected      string
	SuperDisconnecting  string
	SuperReady          string
	WorkerRequested     string
	ErrNetwork          string
	ErrHandlerTimeout   string
	Start               string
	Healthcheck         string
	Heartbeat           string
	ServerPayload       string
}

// ClientGroupsDef contains all the state groups of the Client state schema.
type ClientGroupsDef struct{}

// ClientSchema represents all relations and properties of ClientStates.
var ClientSchema = am.Schema{
	ssC.ErrHandlerTimeout: {
		Add:     S{ssC.Exception},
		Multi:   true,
		Require: S{ssC.Exception},
	},
	ssC.ErrNetwork: {
		Add:     S{ssC.Exception},
		Multi:   true,
		Require: S{ssC.Exception},
	},
	ssC.ErrSupervisor: {Require: S{ssC.Exception}},
	ssC.ErrWorker:     {Require: S{ssC.Exception}},
	ssC.Exception:     {Multi: true},
	ssC.Healthcheck:   {Multi: true},
	ssC.Heartbeat:     {},
	ssC.Ready: {
		Auto:    true,
		Require: S{ssC.WorkerReady},
	},
	ssC.ServerPayload:       {Multi: true},
	ssC.Start:               {},
	ssC.SuperConnected:      {},
	ssC.SuperConnecting:     {},
	ssC.SuperDisconnected:   {},
	ssC.SuperDisconnecting:  {},
	ssC.SuperReady:          {},
	ssC.WorkerConnected:     {},
	ssC.WorkerConnecting:    {},
	ssC.WorkerDisconnected:  {},
	ssC.WorkerDisconnecting: {},
	ssC.WorkerReady:         {Remove: S{ssC.WorkerRequested}},
	ssC.WorkerRequested:     {Require: S{ssC.SuperReady}},
}

// EXPORTS AND GROUPS
var (
	ssC = ClientStatesDef{
		ErrHandlerTimeout:   "ErrHandlerTimeout",
		ErrNetwork:          "ErrNetwork",
		ErrSupervisor:       "ErrSupervisor",
		ErrWorker:           "ErrWorker",
		Healthcheck:         "Healthcheck",
		Heartbeat:           "Heartbeat",
		Ready:               "Ready",
		ServerPayload:       "ServerPayload",
		Start:               "Start",
		StatesBase:          &am.StatesBase{Exception: "Exception"},
		SuperConnected:      "SuperConnected",
		SuperConnecting:     "SuperConnecting",
		SuperDisconnected:   "SuperDisconnected",
		SuperDisconnecting:  "SuperDisconnecting",
		SuperReady:          "SuperReady",
		WorkerConnected:     "WorkerConnected",
		WorkerConnecting:    "WorkerConnecting",
		WorkerDisconnected:  "WorkerDisconnected",
		WorkerDisconnecting: "WorkerDisconnecting",
		WorkerReady:         "WorkerReady",
		WorkerRequested:     "WorkerRequested",
	}
	sgC = ClientGroupsDef{}

	// ClientStates contains all the states for the Client state schema.
	ClientStates = ssC

	// ClientGroups contains all the state groups for the Client state schema.
	ClientGroups = sgC
)

func init() {
	ssC.SetNames(S{"Exception", "ErrWorker", "ErrSupervisor", "WorkerDisconnected", "WorkerConnecting", "WorkerConnected", "WorkerDisconnecting", "WorkerReady", "Ready", "SuperDisconnected", "SuperConnecting", "SuperConnected", "SuperDisconnecting", "SuperReady", "WorkerRequested", "ErrNetwork", "ErrHandlerTimeout", "Start", "Healthcheck", "Heartbeat", "ServerPayload"})
	groups := map[string][]int{}
	ssC.SetStateGroups(groups, []string{})
}
