// Code generated by am-gen; DO NOT EDIT.
//go:build tinygo

package states

import am "github.com/pancsta/asyncmachine-go/pkg/machine"

// S is a type alias for a list of state names.
type S = am.S

// ///// ///// /////

// ///// FILE

// ///// ///// /////

// FileStatesDef contains states for File.
type FileStatesDef struct {
	*am.StatesBase
	DownloadingFile string
	FileDownloaded  string
	ProcessingFile  string
	FileProcessed   string
	UploadingFile   string
	FileUploaded    string
}

// FileGroupsDef contains all the state groups of the File state schema.
type FileGroupsDef struct {
	Uploaded   S
	Downloaded S
	Processed  S
}

// FileSchema represents all relations and properties of FileStates.
var FileSchema = am.Schema{
	ssF.DownloadingFile: {Remove: S{ssF.DownloadingFile, ssF.FileDownloaded}},
	ssF.Exception:       {},
	ssF.FileDownloaded:  {Remove: S{ssF.DownloadingFile, ssF.FileDownloaded}},
	ssF.FileProcessed:   {Remove: S{ssF.ProcessingFile, ssF.FileProcessed}},
	ssF.FileUploaded:    {Remove: S{ssF.UploadingFile, ssF.FileUploaded}},
	ssF.ProcessingFile: {
		Auto:    true,
		Remove:  S{ssF.ProcessingFile, ssF.FileProcessed},
		Require: S{ssF.FileDownloaded},
	},
	ssF.UploadingFile: {
		Auto:    true,
		Remove:  S{ssF.UploadingFile, ssF.FileUploaded},
		Require: S{ssF.FileProcessed},
	},
}

// EXPORTS AND GROUPS
var (
	ssF = FileStatesDef{
		DownloadingFile: "DownloadingFile",
		FileDownloaded:  "FileDownloaded",
		FileProcessed:   "FileProcessed",
		FileUploaded:    "FileUploaded",
		ProcessingFile:  "ProcessingFile",
		StatesBase:      &am.StatesBase{Exception: "Exception"},
		UploadingFile:   "UploadingFile",
	}
	sgF = FileGroupsDef{
		Downloaded: S{ssF.DownloadingFile, ssF.FileDownloaded},
		Processed:  S{ssF.ProcessingFile, ssF.FileProcessed},
		Uploaded:   S{ssF.UploadingFile, ssF.FileUploaded},
	}

	// FileStates contains all the states for the File state schema.
	FileStates = ssF

	// FileGroups contains all the state groups for the File state schema.
	FileGroups = sgF
)

func init() {
	ssF.SetNames(S{"Exception", "DownloadingFile", "FileDownloaded", "ProcessingFile", "FileProcessed", "UploadingFile", "FileUploaded"})
	groups := map[string][]int{
		"Downloaded": {1, 2},
		"Processed":  {3, 4},
		"Uploaded":   {5, 6},
	}
	ssF.SetStateGroups(groups, []string{"Uploaded", "Downloaded", "Processed"})
}
